device_list_name: Reolink Duo 3 PoE
ipc:
  display:
    desc: 设置>显示
    items:
      display:

        date:
          desc: 设置>显示>日期
          name: 日期
          options:
          - 隐藏
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          text:
          - 日期
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏
          type: popup

        day_and_night:
          black_and_white:
            desc: 白天和黑夜>黑白
            name: 黑白
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 黑白
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          day_color:
            desc: 白天和黑夜>白天彩色
            name: 白天彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 白天彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          desc: 白天和黑夜
          mode_switching:
            desc: 白天和黑夜>模式切换
            name: 模式切换
            options:
            - 黑白
            - 彩色
            - 自动
            - 日夜切换阈值
            text:
            - 模式切换
            - 黑白
            - 彩色
            - 自动
            - 光线较亮时自动显示彩色，较暗时自动显示黑白。
            - 日夜切换阈值
            - 白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：
            - 恢复默认值
            - '0'
            - '100'
            type: popup
          name: 白天和黑夜
          night_vision_color:
            desc: 白天和黑夜>夜视彩色
            name: 夜视彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 夜视彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          options:
          - 模式切换
          - 黑白
          - 白天彩色
          - 夜视彩色
          text:
          - 白天和黑夜
          - 模式切换
          - 高光/阴影调节
          - 黑白
          - 白天彩色
          - 夜视彩色
          type: popup

        device_name:
          desc: 设置>显示>设备名称
          name: 设备名称
          options:
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏
          text:
          - 设备名称
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏
          type: popup

        image_setting:
          name: '图像设置(只需要确认亮度同步/hdr/夜视通透模式/抗闪烁)'

          brightness: '亮度'
          contrast: '对比度'
          saturation: '饱和度'
          sharpness: '锐度'
          brightness_sync: false
          hdr: false
          night_transparent_vision: false
          anti_flicker: true

        options:
        - 码流
        - 设备名称
        - 日期
        - 水印
        - 图像设置
        - 白天和黑夜
        - 遮盖区域
        - 拼接设置

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 4

        splice_region:
          desc: 设置>显示>拼接设置
          name: 拼接设置
          options:
          - 距离（米）
          - 水平
          - 垂直
          text:
          - 拼接设置
          - 拼接距离
          - 距离（米）
          - 在你设置的距离附近，拼接画面会达到最佳观看效果
          - 拼接位置
          - 水平
          - 垂直
          - 调整左右两个画面之间的水平或垂直距离差，以达到最佳观看效果
          - 恢复默认设置
          type: navigation

        stream:
          clear:
            frame_rate:
              desc: 设置>显示>码流>码流>清晰>帧率(FPS)
              name: 帧率(FPS)
              options:
              - 20(默认)
              - '18'
              - '16'
              - '15'
              - '12'
              - '10'
              - '8'
              - '6'

            i_frame_interval:
              desc: 设置>显示>码流>码流>清晰>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x

            max_bit_rate:
              desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
              name: 最大码率(Kbps)
              options:
              - '3072'
              - '4096'
              - '5120'
              - '6144'
              - '7168'
              - '8192'
              - '9216'
              - 10240(默认)

            resolution:
              desc: 设置>显示>码流>码流>清晰>分辨率
              name: 分辨率
              options:
              - 7680*2160
              - 4096*1152

            text:
            - I 帧间隔

          fluent:
            frame_rate:
              desc: 设置>显示>码流>码流>流畅>帧率(FPS)
              name: 帧率(FPS)
              options:
              - 20(默认)
              - '15'
              - '10'
              - '7'
              - '4'

            i_frame_interval:
              desc: 设置>显示>码流>码流>流畅>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x
              - 3x
              - 4x

            max_bit_rate:
              desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
              options:
              - '256'
              - '512'
              - 1024(默认)
              - '1536'
              - '2048'

            resolution:
              desc: 设置>显示>码流>码流>流畅>分辨率
              name: 分辨率
              options:
              - 1536*432

            text:
            - I 帧间隔

          frame_rate_mode:
            name: '帧率控制(A代表自动，B代表恒定，C代表逐步)'
            desc: '设置>显示>码流>码流>帧率控制'
            support_mode: 'ABC'

          rate_mode:
            desc: 设置>显示>码流>码流>码率模式
            name: 码率控制
            options:
            - 固定码率
            - 动态码率
            text:
            - 码率控制
            - 固定码率
            - 不同的码率控制模式会影响画质和文件存储大小。
            - 动态码率
            - 自动根据视频内容的复杂度进行码率控制。码率不足时，视频可能会变得模糊。
            type: popup
          text:
            - I 帧间隔
          options:
            - '帧率控制'
            - '码率控制'

        text:
        - 码流
        - 设备名称
        - 日期
        - 水印
        - 图像设置
        - 白天和黑夜
        - 遮盖区域

        type: navigation

        watermark: 水印

uid: 952700Y1007SIHX8
