device_list_name: "Reolink Argus 2E-02"
uid: '952700Y003RVQ9WU'

ipc:
  display:
    name: '显示'
    desc: '设置>显示'
    type: 'navigation'

    items:
      display:
        name: '显示'
        desc: '设置>显示'
        type: 'navigation'
        text:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '移动标记'
          - '画面为清晰时，智能检测到移动事物将进行标记。'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'
          - '场景'
        options:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '移动标记'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'
          - '场景'

        vertical_flip:
          name: '垂直翻转'
          desc: '设置>显示>垂直翻转'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        horizontal_flip:
          name: '水平翻转'
          desc: '设置>显示>水平翻转'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        stream:
          text:
            - 'I 帧间隔'
          options:
            - ''

          clear:
            text:
              - 'I 帧间隔'

            resolution:
              name: '分辨率'
              options:
                - '2304*1296'

            frame_rate:
              name: '帧率(FPS)'
              options:
                - '15(默认)'
                - '12'
                - '10'

            max_bit_rate:
              name: '最大码率(kbps)'
              options:
                - '1024'
                - '1536'
                - '2048(默认)'

            i_frame_interval:
              name: 'I 帧间隔'
              options:
                - '1x'
                - '2x'

          fluent:
            text:
              - 'I 帧间隔'

            resolution:
              name: '分辨率'
              options:
                - '640*360'

            frame_rate:
              name: '帧率(FPS)'
              options:
                - '15(默认)'
                - '10'

            max_bit_rate:
              desc: '最大码率(kbps)'
              options:
                - '64'
                - '128'
                - '160'
                - '192(默认)'
                - '256'

            i_frame_interval:
              name: 'I 帧间隔'
              options:
                - '1x'
                - '2x'
                - '3x'
                - '4x'

        device_name:
          name: '设备名称'
          desc: '设置>显示>设备名称'
          type: 'popup'
          text:
            - '设备名称'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'
          options:
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'

        date:
          name: '日期'
          desc: '设置>显示>日期'
          type: 'popup'
          text:
            - '日期'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'
          options:
            - '隐藏'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'

        watermark:
          name: '水印'
          desc: '设置>显示>水印'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        image_setting:
          name: '图像设置(只需要确认亮度同步/hdr/夜视通透模式/抗闪烁)'

          brightness: '亮度'
          contrast: '对比度'
          saturation: '饱和度'
          sharpness: '锐度'
          brightness_sync: false
          hdr: false
          night_transparent_vision: false
          anti_flicker: true

        day_and_night:
          name: '白天和黑夜'
          desc: '白天和黑夜'
          type: 'popup'
          text:
            - '白天和黑夜'
            - '模式切换'
            - '高光/阴影调节'
            - '黑白'
            - '白天彩色'
          options:
            - '模式切换'
            - '黑白'
            - '白天彩色'

          mode_switching:
            name: '模式切换'
            desc: '白天和黑夜>模式切换'
            type: 'popup'
            text:
              - '模式切换'
              - '黑白'
              - '彩色'
              - '自动'
              - '光线较亮时自动显示彩色，较暗时自动显示黑白。'
            options:
              - '黑白'
              - '彩色'
              - '自动'

          day_color:
            name: '白天彩色'
            desc: '白天和黑夜>白天彩色'
            type: 'popup'
            text:
              - '白天彩色'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

          black_and_white:
            name: '黑白'
            desc: '白天和黑夜>黑白'
            type: 'popup'
            text:
              - '黑白'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

        scenes:
          name: '场景'

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 8
