model: 'Reolink Doorbell Battery'
desc: '设置>Wi-Fi'
page:
  page_title: 'Wi-Fi'
  nav_list:
    - item: 'Wi-Fi测速'
      default: []
      option:
        - '开始测速'
      expected_result: []
    - item: '输入密码'
      option:
        - 'wifi名称'
        - 'wifi密码'
      expected_result: []