device_list_name: "Reolink Doorbell Battery"
sub_name: ""
access_mode: "single"
uid: "952700Y0061K137Z"
desc: '设置>Wi-Fi'
sub_pages:
  wifi:
    expected_page_title: "Wi-Fi"
    expected_texts:
      - "Wi-Fi测速"
      - "检测局域网设备当前的Wi-Fi信号强度"
      - "lumos_5G"
      - "当前Wi-Fi"
      - "切换Wi-Fi"
      - "添加其他网络"
    excluded_texts: []
    xml_az_parse_conditions:
      package: "com.mcu.reolink"
      class: "android.widget.TextView"
      index: "0"
      enabled: "true"
      text: { not_equal: "" }
      resource-id: { not_equal: "com.mcu.reolink:id/device_name_tv" }
    xml_ios_parse_conditions:
      type: "XCUIElementTypeStaticText"
      index: "0"
      accessible: { not_equal: "false" }
  wifi_speed_test:
    page_title: "Wi-Fi测速"
    expected_texts:
      - "1. 关闭手机移动数据，将手机与设备连接至同一个网络。"
      - "2. 点击“开始测速”测试Wi-Fi信号强度，并将手机和设备尽量靠近路由器。"
      - "3. 查看Wi-Fi信号强度测试结果，正常情况下，需要保证Wi-Fi信号强度在10Mbps以上（总值100Mbps）。"
      - "开始测速"
    excluded_texts: []
    xml_az_parse_conditions:
      package: "com.mcu.reolink"
      class: "android.widget.TextView"
      index: "0"
      enabled: "true"
      text: { not_equal: "" }
      resource-id: { not_equal: "com.mcu.reolink:id/network_option_tv" }
    xml_ios_parse_conditions:
      type: "XCUIElementTypeStaticText"
      index: "0"
      accessible: { not_equal: "false" }
  add_additional_networks:
    page_title: "输入密码"
    expected_texts:
      - "Wi-Fi名称"
      - "Wi-Fi密码"
      - "取消"
      - "保存"
    excluded_texts: []
    xml_az_parse_conditions:
      package: "com.mcu.reolink"
      class: "android.widget.EditText"
      index: "0"
      enabled: "true"
      text: { equal: "" }
      resource-id: { not_equal: "com.mcu.reolink:id/username_et" }
    xml_ios_parse_conditions:
      type: "XCUIElementTypeTextField"
      index: "0"
      accessible: { not_equal: "false" }