device_list_name: E1-samll-ball-chicken
uid: 952700Y001Y4QYPQ

ipc:
  display:
    items:
      display:
        text:
          - 垂直翻转
          - 水平翻转
          - 码流
          - 移动标记
          - 画面为清晰时，智能检测到移动事物将进行标记。
          - 设备名称
          - 日期
          - 水印
          - 图像设置
          - 白天和黑夜
          - 遮盖区域
        options:
          - 垂直翻转
          - 水平翻转
          - 码流
          - 移动标记
          - 设备名称
          - 日期
          - 水印
          - 图像设置
          - 白天和黑夜
          - 遮盖区域

        date:
          desc: 设置>显示>日期
          name: 日期
          options:
          - 隐藏
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
        day_and_night:
          black_and_white:
            desc: 白天和黑夜>黑白
            name: 黑白
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 黑白
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          day_color:
            desc: 白天和黑夜>白天彩色
            name: 白天彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 白天彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          desc: 白天和黑夜
          mode_switching:
            desc: 白天和黑夜>模式切换
            name: 模式切换
            options:
            - 黑白
            - 彩色
            - 自动
            - 日夜切换阈值
            text:
            - 模式切换
            - 黑白
            - 彩色
            - 自动
            - 光线较亮时自动显示彩色，较暗时自动显示黑白。
            - 日夜切换阈值
            - 白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：
            - 恢复默认值
            - '0'
            - '100'
            type: popup
          name: 白天和黑夜
          night_vision_color:
            desc: 白天和黑夜>夜视彩色
            name: 夜视彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 夜视彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          options:
          - 模式切换
          - 黑白
          - 白天彩色
          - 夜视彩色
          text:
          - 白天和黑夜
          - 模式切换
          - 高光/阴影调节
          - 黑白
          - 白天彩色
          - 夜视彩色
          type: popup


        device_name:
          desc: 设置>显示>设备名称
          name: 设备名称
          options:
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏
        horizontal_flip: 水平翻转

        image_setting:
          name: '图像设置(只需要确认亮度同步/hdr/夜视通透模式/抗闪烁)'

          brightness: '亮度'
          contrast: '对比度'
          saturation: '饱和度'
          sharpness: '锐度'
          brightness_sync: false
          hdr: false
          night_transparent_vision: false
          anti_flicker: true

        motion_mark: 移动标记

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 4

        stream:
          text:
            - I 帧间隔
            - 帧率控制
          options:
            - '帧率控制'

          clear:
            frame_rate:
              desc: 设置>显示>码流>码流>清晰>帧率(FPS)
              name: 帧率(FPS)
              options:
              - '20'
              - '18'
              - '16'
              - 15(默认)
              - '12'
              - '10'
              - '8'
              - '6'
              text:
              - 帧率(FPS)
              - 每秒钟的帧数，越高画面越流畅
              - '20'
              - '18'
              - '16'
              - 15(默认)
              - '12'
              - '10'
              - '8'
              - '6'
              type: popup
            i_frame_interval:
              desc: 设置>显示>码流>码流>清晰>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x
              text:
              - I 帧间隔
              - I帧间隔小，视频质量高，但文件大。I帧间隔大，文件小，但质量低。
              - 1x
              - 2x
              type: popup
            max_bit_rate:
              desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
              name: 最大码率(Kbps)
              options:
              - '4096'
              - 2560(默认)
              - '1024'
              - '1536'
              - '2048'
              - '3072'
              text:
              - 最大码率(Kbps)
              - 相同的分辨率、帧率下，码率越大画质越好，网络要求也越高
              - '1024'
              - '1536'
              - '2048'
              - 2560(默认)
              - '3072'
              - '4096'
              type: popup
            resolution:
              desc: 设置>显示>码流>码流>清晰>分辨率
              name: 分辨率
              options:
              - 2304*1296
              text:
              - 分辨率
              - 越高视频越清晰
              - 2304*1296
              type: popup
            text:
            - 取消
            - 清晰
            - 保存
            - 分辨率
            - 帧率(FPS)
            - 最大码率(Kbps)
            - 编码格式
            - I 帧间隔

          fluent:
            frame_rate:
              desc: 设置>显示>码流>码流>流畅>帧率(FPS)
              name: 帧率(FPS)
              options:
              - '4'
              - 10(默认)
              - '7'
              - '15'
              text:
              - 帧率(FPS)
              - 每秒钟的帧数，越高画面越流畅
              - '15'
              - 10(默认)
              - '7'
              - '4'
              type: popup
            i_frame_interval:
              desc: 设置>显示>码流>码流>流畅>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x
              - 3x
              - 4x
              text:
              - I 帧间隔
              - I帧间隔小，视频质量高，但文件大。I帧间隔大，文件小，但质量低。
              - 1x
              - 2x
              - 3x
              - 4x
              type: popup
            max_bit_rate:
              desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
              options:
              - '512'
              - '160'
              - '192'
              - '256'
              - 384(默认)
              - '128'
              text:
              - 最大码率(Kbps)
              - 相同的分辨率、帧率下，码率越大画质越好，网络要求也越高
              - '128'
              - '160'
              - '192'
              - '256'
              - 384(默认)
              - '512'
              type: popup
            resolution:
              desc: 设置>显示>码流>码流>流畅>分辨率
              name: 分辨率
              options:
              - 704*480
              text:
              - 分辨率
              - 越高视频越清晰
              - 704*480
              type: popup
            text:
            - 取消
            - 流畅
            - 保存
            - 分辨率
            - 帧率(FPS)
            - 最大码率(Kbps)
            - 编码格式
            - I 帧间隔

          frame_rate_mode:
            name: '帧率控制(A代表自动，B代表恒定，C代表逐步)'
            desc: '设置>显示>码流>码流>帧率控制'
            support_mode: 'ABC'

        vertical_flip: 垂直翻转

        watermark: 水印


