device_list_name: RLC-1224A
ipc:
  display:
    desc: 设置>显示
    items:
      display:
        date:
          desc: 设置>显示>日期
          name: 日期
          options:
          - 隐藏
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          text:
          - 日期
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏
          type: popup
        day_and_night:
          black_and_white:
            desc: 白天和黑夜>黑白
            name: 黑白
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 黑白
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          day_color:
            desc: 白天和黑夜>白天彩色
            name: 白天彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 白天彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          desc: 白天和黑夜
          mode_switching:
            desc: 白天和黑夜>模式切换
            name: 模式切换
            options:
            - 黑白
            - 彩色
            - 自动
            - 日夜切换阈值
            text:
            - 模式切换
            - 黑白
            - 彩色
            - 自动
            - 光线较亮时自动显示彩色，较暗时自动显示黑白。
            - 日夜切换阈值
            - 白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：
            - 恢复默认值
            - '0'
            - '100'
            type: popup
          name: 白天和黑夜
          night_vision_color:
            desc: 白天和黑夜>夜视彩色
            name: 夜视彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 夜视彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          options:
          - 模式切换
          - 黑白
          - 白天彩色
          - 夜视彩色
          text:
          - 白天和黑夜
          - 模式切换
          - 高光/阴影调节
          - 黑白
          - 白天彩色
          - 夜视彩色
          type: popup
        desc: 设置>显示
        device_name:
          desc: 设置>显示>设备名称
          name: 设备名称
          options:
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏
          text:
          - 设备名称
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏
          type: popup
        horizontal_flip:
          desc: 设置>显示>水平翻转
          name: 水平翻转
          options:
          - switch_on
          - switch_off
          type: switch
        image_setting:
          anti_flicker:
            desc: 设置>显示>抗闪烁
            name: 抗闪烁
            options:
            - 50HZ
            - 60HZ
            - 其他
            - 关闭
            text:
            - 抗闪烁
            - 50HZ
            - 60HZ
            - 其他
            - 关闭
            type: popup
          brightness:
            name: 亮度
          contrast:
            name: 对比度
          desc: 设置>显示>图像设置
          name: 图像设置
          night_transparent_vision:
            desc: 设置>显示>夜视通透模式
            name: 夜视通透模式
            options:
            - switch_on
            - switch_off
            text:
            - ''
            type: switch
          saturation:
            name: 饱和度
          sharpness:
            name: 锐度
          text:
          - 亮度
          - 对比度
          - 饱和度
          - 锐度
          - 抗闪烁
          - 调整摄像机的拍摄帧率，以减少受到画面中光源闪烁的影响。
          - 夜视通透模式
          - 优化夜视模式下的画面亮度。
          - '0'
          - '255'
          type: page
        motion_mark:
          desc: 设置>显示>移动标记
          name: 移动标记
          options:
          - switch-on
          - switch-off
          text:
          - 移动标记
          - 画面为清晰时，智能检测到移动事物将进行标记。
          type: switch
        name: 显示
        options:
        - 垂直翻转
        - 水平翻转
        - 码流
        - 移动标记
        - 设备名称
        - 日期
        - 水印
        - 图像设置
        - 白天和黑夜
        - 遮盖区域
        private_mark:
          desc: 设置>显示>遮盖区域
          name: 遮盖区域
          text:
          - 取消
          - 遮盖区域
          - 保存
          - 清空所有
          type: navigation
          user_tips:
          - 在画面中通过手指滑动添加黑色遮挡区域，监控视频中的遮挡区域将不可见，最多可遮挡4个区域。
          - 我知道了
        stream:
          desc: 设置>显示>码流
          name: 码流
          subpage:
            clear:
              desc: 设置>显示>码流>码流>清晰
              name: 清晰
              subpage:
                desc: 设置>显示>码流>码流>清晰
                frame_rate:
                  desc: 设置>显示>码流>码流>清晰>帧率(FPS)
                  name: 帧率(FPS)
                  options:
                  - 20(默认)
                  - '18'
                  - '16'
                  - '15'
                  - '12'
                  - '10'
                  - '8'
                  - '6'
                  text:
                  - 帧率(FPS)
                  - 每秒钟的帧数，越高画面越流畅
                  - 20(默认)
                  - '18'
                  - '16'
                  - '15'
                  - '12'
                  - '10'
                  - '8'
                  - '6'
                  type: popup
                i_frame_interval:
                  desc: 设置>显示>码流>码流>清晰>I 帧间隔
                  name: I 帧间隔
                  options:
                  - 1x
                  - 2x
                  text:
                  - I 帧间隔
                  - I帧间隔小，视频质量高，但文件大。I帧间隔大，文件小，但质量低。
                  - 1x
                  - 2x
                  type: popup
                max_bit_rate:
                  desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
                  name: 最大码率(Kbps)
                  options:
                  - '3072'
                  - '4096'
                  - '5120'
                  - '6144'
                  - '7168'
                  - 8192(默认)
                  - '9126'
                  - '10240'
                  text:
                  - 最大码率(Kbps)
                  - 相同的分辨率、帧率下，码率越大画质越好，网络要求也越高
                  - '3072'
                  - '4096'
                  - '5120'
                  - '6144'
                  - '7168'
                  - 8192(默认)
                  - '9126'
                  - '10240'
                  type: popup
                name: 清晰
                resolution:
                  desc: 设置>显示>码流>码流>清晰>分辨率
                  name: 分辨率
                  options:
                  - 4512*2512
                  - 3840*2160
                  - 2560*1440
                  - 2304*1296
                  text:
                  - 分辨率
                  - 越高视频越清晰
                  - 4512*2512
                  - 3840*2160
                  - 2560*1440
                  - 2304*1296
                  type: popup
                text:
                - 取消
                - 清晰
                - 保存
                - 分辨率
                - 帧率(FPS)
                - 最大码率(Kbps)
                - I 帧间隔
                type: page
              type: navigation
            desc: 设置>显示>码流>码流
            fluent:
              desc: 设置>显示>码流>码流>流畅
              name: 流畅
              subpage:
                desc: 设置>显示>码流>码流>流畅
                frame_rate:
                  desc: 设置>显示>码流>码流>流畅>帧率(FPS)
                  name: 帧率(FPS)
                  options:
                  - '20'
                  - '15'
                  - 10(默认)
                  - '7'
                  - '4'
                  text:
                  - 帧率(FPS)
                  - 每秒钟的帧数，越高画面越流畅
                  - '20'
                  - '15'
                  - 10(默认)
                  - '7'
                  - '4'
                  type: popup
                interval_frame:
                  desc: 设置>显示>码流>码流>流畅>I 帧间隔
                  name: I 帧间隔
                  options:
                  - 1x
                  - 2x
                  - 3x
                  - 4x
                  text:
                  - I 帧间隔
                  - I帧间隔小，视频质量高，但文件大。I帧间隔大，文件小，但质量低。
                  - 1x
                  - 2x
                  - 3x
                  - 4x
                  type: popup
                max_bit_rate:
                  desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
                  options:
                  - '128'
                  - '256'
                  - '384'
                  - '512'
                  - '672'
                  - '768'
                  - 1024(默认)
                  - '1228'
                  text:
                  - 最大码率(Kbps)
                  - 相同的分辨率、帧率下，码率越大画质越好，网络要求也越高
                  - '128'
                  - '256'
                  - '384'
                  - '512'
                  - '672'
                  - '768'
                  - 1024(默认)
                  - '1228'
                  type: popup
                name: 流畅
                resolution:
                  desc: 设置>显示>码流>码流>流畅>分辨率
                  name: 分辨率
                  options:
                  - 896*512
                  text:
                  - 分辨率
                  - 越高视频越清晰
                  - 896*512
                  type: popup
                text:
                - 取消
                - 流畅
                - 保存
                - 分辨率
                - 帧率(FPS)
                - 最大码率(Kbps)
                - 编码格式
                - I 帧间隔
                type: page
              type: navigation
            frame_rate_mode:
              desc: 设置>显示>码流>码流>帧率控制
              name: 帧率控制
              options:
              - 自动
              - 恒定
              text:
              - 帧率控制
              - 自动
              - 可变帧率，自动调节帧率来保持画质（不适用有快速运动的物体）。
              - 恒定
              - 恒定帧率，流畅优先。
              type: popup
            name: 码流
            rate_mode:
              desc: 设置>显示>码流>码流>码率模式
              name: 码率控制
              options:
              - 固定码率
              - 动态码率
              text:
              - 码率控制
              - 固定码率
              - 不同的码率控制模式会影响画质和文件存储大小。
              - 动态码率
              - 自动根据视频内容的复杂度进行码率控制。码率不足时，视频可能会变得模糊。
              type: popup
            text:
            - 码流
            - 清晰
            - 分辨率
            - 帧率(FPS)
            - 最大码率(Kbps)
            - 流畅
            - I 帧间隔
            - 帧率控制
            type: navigation
          type: navigation
        text:
        - 垂直翻转
        - 水平翻转
        - 码流
        - 移动标记
        - 画面为清晰时，智能检测到移动事物将进行标记。
        - 设备名称
        - 日期
        - 水印
        - 图像设置
        - 白天和黑夜
        - 遮盖区域
        type: navigation
        vertical_flip:
          desc: 设置>显示>垂直翻转
          name: 垂直翻转
          options:
          - switch_on
          - switch_off
          type: switch
        watermark:
          desc: 设置>显示>水印
          name: 水印
          options:
          - switch_on
          - switch_off
          type: switch
    name: 显示
    type: navigation
uid: 952700Y004OY1G4W
