device_list_name: "Reolink Altas PT Ultra"
uid: '952700Y100BF19GB'
sub_name: ""

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        name: '灯'
        desc: '设置>灯主页'
        type: 'page'
        text:
          - '灯'
          - '状态灯'
          - '红外灯'
          - '照明灯'

        status_lights:
          name: '状态灯'
          desc: '设置>灯>状态灯'
          type: 'navigation'
          subpage:
            name: '状态灯'
            desc: '设置>灯>状态灯'
            type: 'page'
            text:
              - '状态灯'
              - '位于镜头附近的一个表示摄像机连接状态的灯。'
              - '了解更多'
              - '关闭'
              - '状态灯将保持关闭'
              - '开启'
              - '状态灯将始终亮起'

            light_off_mode:
              name: '关闭'
              desc: '设置>灯>状态灯>关闭'
              type: 'menu'

            light_on_mode:
              name: '开启'
              desc: '设置>灯>状态灯>开启'
              type: 'menu'

        floodlight:
          name: '照明灯'
          desc: '设置>灯>照明灯'
          type: 'navigation'
          subpage:
            name: '照明灯'
            desc: '设置>灯>照明灯'
            type: 'page'

            light_off_mode:
              name: '关闭'
              desc: '设置>灯>照明灯>关闭'
              type: 'menu'
              text:
                - '白光灯'
                - '夜晚时开启照明灯画面呈彩色状态，拍摄效果更佳。'
                - '关闭'
                - '白光灯将保持关闭'

            auto_mode:
              name: '自动模式'
              desc: '设置>灯>照明灯>自动模式'
              type: 'menu'
              text:
                - '白光灯'
                - '夜晚时开启照明灯画面呈彩色状态，拍摄效果更佳。'
                - '关闭'
                - '白光灯将保持关闭'
                - '自动模式'
                - '根据环境光照条件自动调整亮度以获得最佳夜视效果。'
