device_list_name: Reolink Lumus
ipc:
  camera_record:
    desc: 设置>摄像机录像
    items:
      alarm_recording_plan:
        desc: 设置>摄像机录像>报警录像>报警录像计划
        name: 报警录像计划
        text:
        - 取消
        - 报警录像计划
        - 保存
        - 配置报警录像（检测到报警事件时触发录像）的触发类型和时间计划。
        - 报警类型
        type: navigation
      camera_record:
        desc: 设置>摄像机录像
        name: 摄像机录像
        options:
        - 摄像机录像
        - 报警录像计划
        - 录像延时时长
        - 预录像
        text:
        - 摄像机录像
        - 录制监控视频，以便查看回放。
        - 报警录像
        - 报警录像计划
        - 配置报警录像（检测到报警事件时触发录像）的触发类型和时间计划。
        - 录像延时时长
        - 触发事件停止后延后录制的时长
        - 预录像
        - 触发报警前开始录像.
        - 定时录像
        - 定时录像计划
        - 配置持续录像的时间计划，启用的时间段会持续不间断地录像。
        type: navigation
      overwrite_record:
        desc: 设置>摄像机录像>覆盖录像
        name: 覆盖录像
        text:
        - 覆盖录像
        - 当存储空间满时，将覆盖最早的录像文件。
        type: page
      pre_record:
        desc: 设置>摄像机录像>报警录像>预录像
        name: 预录像
        options:
        - ''
        text:
        - ''
        type: switch
      record_delay_duration:
        desc: 设置>摄像机录像>报警录像>录像延时时长
        name: 录像延时时长
        option_text:
        - 15秒
        - 30秒
        - 1分钟
        text:
        - 录像延时时长
        - 延时越长，能耗越大。
        - 15秒
        - 30秒
        - 1分钟
        type: popup
    name: 摄像机录像
    type: navigation
uid: 952700Y006BDF1TT
