device_list_name: "E1 Outdoor Pro"
uid: '952700Z00XMA1WZ1'

ipc:
  display:
    name: '显示'
    desc: '设置>显示'
    type: 'navigation'

    items:
      display:
        name: '显示'
        desc: '设置>显示'
        type: 'navigation'
        text:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '移动标记'
          - '画面为清晰时，智能检测到移动事物将进行标记。'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'
        options:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '移动标记'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'

        vertical_flip:
          name: '垂直翻转'
          desc: '设置>显示>垂直翻转'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        horizontal_flip:
          name: '水平翻转'
          desc: '设置>显示>水平翻转'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        stream:
          name: '码流'
          desc: '设置>显示>码流'
          type: 'navigation'
          subpage:
            name: '码流'
            desc: '设置>显示>码流>码流'
            type: 'navigation'
            text:
              - '码流'
              - '清晰'
              - '分辨率'
              - '帧率(FPS)'
              - '最大码率(kbps)'
              - '流畅'
              - 'i帧间隔'
              - '帧率控制'

            clear:
              name: '清晰'
              desc: '设置>显示>码流>码流>清晰'
              type: 'navigation'
              subpage:
                name: '清晰'
                desc: '设置>显示>码流>码流>清晰'
                type: 'page'
                text:
                  - '取消'
                  - '清晰'
                  - '保存'
                  - '分辨率'
                  - '帧率(fps)'
                  - '最大码率(kbps)'
                  - 'i帧间隔'

                resolution:
                  name: '分辨率'
                  desc: '设置>显示>码流>码流>清晰>分辨率'
                  type: 'popup'
                  text:
                    - '分辨率'
                    - '越高视频越清晰'
                    - '3840*2160'
                    - '2560*1440'
                    - '2304*1296'
                  options:
                    - '3840*2160'
                    - '2560*1440'
                    - '2304*1296'

                frame_rate:
                  name: '帧率(FPS)'
                  desc: '设置>显示>码流>码流>清晰>帧率(FPS)'
                  type: 'popup'
                  text:
                    - '帧率(FPS)'
                    - '每秒钟的帧数，越高画面越流畅'
                    - '25'
                    - '22'
                    - '20(默认)'
                    - '18'
                    - '16'
                    - '15'
                    - '12'
                    - '10'
                  options:
                    - '25'
                    - '22'
                    - '20(默认)'
                    - '18'
                    - '16'
                    - '15'
                    - '12'
                    - '10'

                max_bit_rate:
                  name: '最大码率(kbps)'
                  desc: '设置>显示>码流>码流>清晰>最大码率(Kbps)'
                  type: 'popup'
                  text:
                    - '最大码率(Kbps)'
                    - '相同的分辨率、帧率下，码率越大画质越好，网络要求也越高'
                    - '4096'
                    - '5120(默认)'
                    - '6144'
                    - '7168'
                    - '8192'
                  options:
                    - '4096'
                    - '5120(默认)'
                    - '6144'
                    - '7168'
                    - '8192'

                i_frame_interval:
                  name: 'i帧间隔'
                  desc: '设置>显示>码流>码流>清晰>i帧间隔'
                  type: 'popup'
                  text:
                    - 'i帧间隔'
                    - 'I帧间隔小，视频质量高，但文件大。I帧间隔大，文件小，但质量低。'
                    - '1x'
                    - '2x'
                  options:
                    - '1x'
                    - '2x'

            fluent:
              name: '流畅'
              desc: '设置>显示>码流>码流>流畅'
              type: 'navigation'
              subpage:
                name: '流畅'
                desc: '设置>显示>码流>码流>流畅'
                type: 'page'
                text:
                  - '取消'
                  - '流畅'
                  - '保存'
                  - '分辨率'
                  - '帧率(fps)'
                  - '最大码率(kbps)'
                  - 'i帧间隔'

                resolution:
                  name: '分辨率'
                  desc: '设置>显示>码流>码流>流畅>分辨率'
                  type: 'popup'
                  text:
                    - '分辨率'
                    - '越高视频越清晰'
                    - '640*360'
                  options:
                    - '640*360'

                frame_rate:
                  name: '帧率(FPS)'
                  desc: '设置>显示>码流>码流>流畅>帧率(FPS)'
                  type: 'popup'
                  text:
                    - '帧率(FPS)'
                    - '每秒钟的帧数，越高画面越流畅'
                    - '15'
                    - '10(默认)'
                    - '7'
                    - '4'
                  options:
                    - '15'
                    - '10(默认)'
                    - '7'
                    - '4'

                max_bit_rate:
                  desc: '设置>显示>码流>码流>流畅>最大码率(kbps)'
                  type: 'popup'
                  text:
                    - '最大码率(kbps)'
                    - '相同的分辨率、帧率下，码率越大画质越好，网络要求也越高'
                    - '64'
                    - '128'
                    - '160'
                    - '192'
                    - '256(默认)'
                    - '384'
                    - '512'
                  options:
                    - '64'
                    - '128'
                    - '160'
                    - '192'
                    - '256(默认)'
                    - '384'
                    - '512'

                interval_frame:
                  name: 'i帧间隔'
                  desc: '设置>显示>码流>码流>流畅>i帧间隔'
                  type: 'popup'
                  text:
                    - 'i帧间隔'
                    - 'I帧间隔小，视频质量高，但文件大。I帧间隔大，文件小，但质量低。'
                    - '1x'
                    - '2x'
                    - '3x'
                    - '4x'
                  options:
                    - '1x'
                    - '2x'
                    - '3x'
                    - '4x'

            frame_rate_mode:
              name: '帧率控制'
              desc: '设置>显示>码流>码流>帧率控制'
              type: 'popup'
              text:
                - '帧率控制'
                - '自动'
                - '可变帧率，自动调节帧率来保持画质（不适用有快速运动的物体）。'
                - '恒定'
                - '恒定帧率，流畅优先。'
                - '逐步'
                - '可变帧率，逐步调节帧率来保持画质（适用有快速运动的物体）。'
              options:
                - '自动'
                - '恒定'
                - '逐步'

        motion_mark:
          name: '移动标记'
          desc: '设置>显示>移动标记'
          type: 'switch'
          text:
            - '移动标记'
            - '画面为清晰时，智能检测到移动事物将进行标记。'
          options:
            - 'switch-on'
            - 'switch-off'

        device_name:
          name: '设备名称'
          desc: '设置>显示>设备名称'
          type: 'popup'
          text:
            - '设备名称'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'
          options:
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'

        date:
          name: '日期'
          desc: '设置>显示>日期'
          type: 'popup'
          text:
            - '日期'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'
          options:
            - '隐藏'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'

        watermark:
          name: '水印'
          desc: '设置>显示>水印'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        image_setting:
          name: '图像设置'
          desc: '设置>显示>图像设置'
          type: 'page'
          text:
            - '亮度'
            - '对比度'
            - '饱和度'
            - '锐度'
            - '抗闪烁'
            - '调整摄像机的拍摄帧率，以减少受到画面中光源闪烁的影响。'
            - '0'
            - '255'

          brightness:
            name: '亮度'
          contrast:
            name: '对比度'
          saturation:
            name: '饱和度'
          sharpness:
            name: '锐度'

          anti_flicker:
            name: '抗闪烁'
            desc: '设置>显示>抗闪烁'
            type: 'popup'
            text:
              - '抗闪烁'
              - '50HZ'
              - '60HZ'
              - '其他'
              - '关闭'
            options:
              - '50HZ'
              - '60HZ'
              - '其他'
              - '关闭'

        day_and_night:
          name: '白天和黑夜'
          desc: '白天和黑夜'
          type: 'popup'
          text:
            - '白天和黑夜'
            - '模式切换'
            - '高光/阴影调节'
            - '黑白'
            - '白天彩色'
            - '夜视彩色'
          options:
            - '模式切换'
            - '黑白'
            - '白天彩色'
            - '夜视彩色'

          mode_switching:
            name: '模式切换'
            desc: '白天和黑夜>模式切换'
            type: 'popup'
            text:
              - '模式切换'
              - '黑白'
              - '彩色'
              - '自动'
              - '光线较亮时自动显示彩色，较暗时自动显示黑白。'
              - '日夜切换阈值'
              - '白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：'
              - '恢复默认值'
              - '0'
              - '100'
            options:
              - '黑白'
              - '彩色'
              - '自动'
              - '日夜切换阈值'

          day_color:
            name: '白天彩色'
            desc: '白天和黑夜>白天彩色'
            type: 'popup'
            text:
              - '白天彩色'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

          black_and_white:
            name: '黑白'
            desc: '白天和黑夜>黑白'
            type: 'popup'
            text:
              - '黑白'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

          night_vision_color:
            name: '夜视彩色'
            desc: '白天和黑夜>夜视彩色'
            type: 'popup'
            text:
              - '夜视彩色'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          text:
            - '取消'
            - '遮盖区域'
            - '保存'
            - '广角画面'
            - '长焦画面'
            - '清空所有'
          user_tips:
            - '在画面中通过手指滑动添加黑色遮挡区域，监控视频中的遮挡区域将不可见，最多可遮挡4个区域。'
            - '我知道了'
          wide_angle: True
          telephoto: True
