device_list_name: "yulong-test-sd7"
uid: '952700Y006ZP1IJ5'
sub_name: ""

ipc:
  detection_alarm:
    name: '侦测报警'
    desc: '设置>侦测报警'
    type: 'navigation'
    text:
      - ''

    items:
      detection_alarm:
        name: '侦测报警'
        desc: '设置>侦测报警主页'
        type: 'page'
        text:
          - '侦测报警'
          - '报警类型设置'
          - '人'
          - '车'
          - '动物'
          - 'MD/其他'
          - '非侦测区域'
          - '非侦测区域仅针对人、车、动物、包裹等报警类型生效，对于其他AI侦测功能不生效'
          - '智能追踪'
          - '追踪类型'
          - '追踪方式'
          - '水平追踪范围'
          - '计划'
          - '多久后结束追踪'
          - '目标静止'
          - '目标消失'

      person:
        name: '人'
        desc: '设置>侦测报警>人>报警类型——人'
        type: 'navigation'
        text:
          - '人'
          - '报警类型「人」的相关设置'
          - '目标尺寸'
          - '智能侦测'
          - '0'
          - '100'
          - '延时报警'
          - '检测目标在报警区域内停留的时间超过设置时间将触发报警'
          - '0'
          - '8'
        object_size:
          name: '目标尺寸'
          desc: '设置>侦测报警>目标尺寸'
          type: 'navigation'
          text:
            - '取消'
            - '目标尺寸'
            - '保存'
        smart_detection:
          name: '智能侦测'
          desc: '设置>侦测报警>人>智能侦测'
          type: 'slider'
        alarm_delay:
          name: '延时报警'
          desc: '设置>侦测报警>人>延时报警'
          type: 'slider'

      car:
        name: '车'
        desc: '设置>侦测报警>报警类型——车'
        type: 'navigation'
        text:
          - '车'
          - '报警类型「车」的相关设置'
          - '目标尺寸'
          - '智能侦测'
          - '0'
          - '100'
          - '延时报警'
          - '检测目标在报警区域内停留的时间超过设置时间将触发报警'
          - '0'
          - '8'
        object_size:
          name: '目标尺寸'
          desc: '设置>侦测报警>车>目标尺寸'
          type: 'navigation'
          text:
            - '取消'
            - '目标尺寸'
            - '保存'
        smart_detection:
          name: '智能侦测'
          desc: '设置>侦测报警>车>智能侦测'
          type: 'slider'
        alarm_delay:
          name: '延时报警'
          desc: '设置>侦测报警>车>延时报警'
          type: 'slider'

      animal:
        name: '动物'
        desc: '设置>侦测报警>报警类型——动物'
        type: 'navigation'
        text:
          - '动物'
          - '报警类型「动物」的相关设置'
          - '目标尺寸'
          - '智能侦测'
          - '0'
          - '100'
          - '延时报警'
          - '检测目标在报警区域内停留的时间超过设置时间将触发报警'
          - '0'
          - '8'
        object_size:
          name: '目标尺寸'
          desc: '设置>侦测报警>动物>目标尺寸'
          type: 'navigation'
          text:
            - '取消'
            - '目标尺寸'
            - '保存'
        smart_detection:
          name: '智能侦测'
          desc: '设置>侦测报警>动物>智能侦测'
          type: 'slider'
        alarm_delay:
          name: '延时报警'
          desc: '设置>侦测报警>动物>延时报警'
          type: 'slider'

      motion_detection:
        name: 'MD/其他'
        desc: '设置>侦测报警>MD/其他'
        type: 'navigation'
        text:
          - 'MD/其他'
          - '全天灵敏度计划表'
          - '全时段灵敏度'
          - '灵敏度高，检测到细微的物体移动就报警，不放过任何风吹草动，如细小的蚊虫、较远的人等。'
          - '0'
          - '50'
          - '添加分段灵敏度'
        add_multi_time_sensitivity:
          name: '添加灵敏度分段'
          desc: '设置>侦测报警>MD/其他>添加灵敏度分段'
          type: 'navigation'
          text:
            - '取消'
            - '编辑分段'
            - '保存'
            - '开始时间'
            - '未设置'
            - '结束时间'
            - '灵敏度'
            - '灵敏度高，检测到细微的物体移动就报警，不放过任何风吹草动，如细小的蚊虫、较远的人等。'
            - '0'
            - '50'

      non_detection_area:
        name: '非侦测区域'
        desc: '设置>侦测报警>非侦测区域'
        type: 'navigation'
        text:
          - '取消'
          - '非侦测区域'
          - '保存'
          - '绘制不需要报警的区域'
          - '全部绘制'

      smart_tracking:
        name: '智能追踪'
        desc: '设置>侦测报警>智能追踪'
        type: 'switch'
        text:
          - '追踪类型'
          - '追踪方式'
          - '水平追踪范围'
          - '计划'
          - '多久后结束追踪'
          - '目标静止'
          - '目标消失'

        tracking_type:
          name: '追踪类型'
          desc: '设置>侦测报警>智能追踪>追踪类型'
          type: 'popup'
          text:
            - '追踪类型'
            - '保存'
            - '全选'
            - '人'
            - '车'
            - '动物'
          option_text:
            - '人'
            - '车'
            - '动物'

        tracking_mode:
          name: '追踪方式'
          desc: '设置>侦测报警>智能追踪>追踪方式'
          type: 'popup'
          text:
            - '追踪方式'
            - '数码'
            - '数码优先'
            - 'PT优先'
          option_text:
            - '数码'
            - '数码优先'
            - 'PT优先'

        horizontal_tracking_range:
          name: '水平追踪范围'
          desc: '设置>侦测报警>智能追踪>水平追踪范围'
          type: 'navigation'
          text:
            - '水平追踪范围'
            - '通过调整左侧和右侧最大旋转角度视图，来限制摄像头的自动水平追踪范围。'
            - '设置'
          left_side_text:
            - '取消'
            - '左侧'
            - '下一步'
            - '设置最大左转角度'
          right_side_text:
            - '上一步'
            - '右侧'
            - '保存'
            - '设置最大右转角度'

        time_plan:
          name: '计划表'
          desc: '设置>侦测报警>智能追踪>计划表'
          type: 'navigation'
          text:
            - '取消'
            - '计划'
            - '保存'
            - '报警'
            - '该时间段内检测到移动事件时会进行录像。'
            - '定时'
            - '该时间段内会持续录像，并标识出报警录像。'
            - '涂抹以选择录像时间'

        object_stops:
          name: '目标静止'
          desc: '设置>侦测报警>智能追踪>目标静止'
          type: 'popup'
          option_text:
            - '10 秒'
            - '20 秒'
            - '30 秒'
            - '60 秒'

        object_disappears:
          name: '目标消失'
          desc: '设置>侦测报警>智能追踪>目标消失'
          type: 'popup'
          option_text:
            - '10 秒'
            - '20 秒'
            - '30 秒'
            - '60 秒'


