device_list_name: yulong-test-sd7
ipc:
  detection_alarm:
    desc: 设置>侦测报警
    items:
      animal:
        alarm_delay:
          desc: 设置>侦测报警>动物>延时报警
          name: 延时报警
          type: slider
        desc: 设置>侦测报警>报警类型——动物
        name: 动物
        object_size:
          desc: 设置>侦测报警>动物>目标尺寸
          name: 目标尺寸
          text:
          - 取消
          - 目标尺寸
          - 保存
          type: navigation
        smart_detection:
          desc: 设置>侦测报警>动物>智能侦测
          name: 智能侦测
          type: slider
        text:
        - 动物
        - 报警类型「动物」的相关设置
        - 目标尺寸
        - 智能侦测
        - '0'
        - '100'
        - 延时报警
        - 检测目标在报警区域内停留的时间超过设置时间将触发报警
        - '0'
        - '8'
        type: navigation
      car:
        alarm_delay:
          desc: 设置>侦测报警>车>延时报警
          name: 延时报警
          type: slider
        desc: 设置>侦测报警>报警类型——车
        name: 车
        object_size:
          desc: 设置>侦测报警>车>目标尺寸
          name: 目标尺寸
          text:
          - 取消
          - 目标尺寸
          - 保存
          type: navigation
        smart_detection:
          desc: 设置>侦测报警>车>智能侦测
          name: 智能侦测
          type: slider
        text:
        - 车
        - 报警类型「车」的相关设置
        - 目标尺寸
        - 智能侦测
        - '0'
        - '100'
        - 延时报警
        - 检测目标在报警区域内停留的时间超过设置时间将触发报警
        - '0'
        - '8'
        type: navigation
      detection_alarm:
        desc: 设置>侦测报警主页
        name: 侦测报警
        text:
        - 侦测报警
        - 报警类型设置
        - 人
        - 车
        - 动物
        - MD/其他
        - 非侦测区域
        - 非侦测区域仅针对人、车、动物、包裹等报警类型生效，对于其他AI侦测功能不生效
        - 智能追踪
        - 追踪类型
        - 追踪方式
        - 水平追踪范围
        - 计划
        - 多久后结束追踪
        - 目标静止
        - 目标消失
        type: page
      motion_detection:
        add_multi_time_sensitivity:
          desc: 设置>侦测报警>MD/其他>添加灵敏度分段
          name: 添加灵敏度分段
          text:
          - 取消
          - 编辑分段
          - 保存
          - 开始时间
          - 未设置
          - 结束时间
          - 灵敏度
          - 灵敏度高，检测到细微的物体移动就报警，不放过任何风吹草动，如细小的蚊虫、较远的人等。
          - '0'
          - '50'
          type: navigation
        desc: 设置>侦测报警>MD/其他
        name: MD/其他
        text:
        - MD/其他
        - 全天灵敏度计划表
        - 全时段灵敏度
        - 灵敏度高，检测到细微的物体移动就报警，不放过任何风吹草动，如细小的蚊虫、较远的人等。
        - '0'
        - '50'
        - 添加分段灵敏度
        type: navigation
      non_detection_area:
        desc: 设置>侦测报警>非侦测区域
        name: 非侦测区域
        text:
        - 取消
        - 非侦测区域
        - 保存
        - 绘制不需要报警的区域
        - 全部绘制
        type: navigation
      person:
        alarm_delay:
          desc: 设置>侦测报警>人>延时报警
          name: 延时报警
          type: slider
        desc: 设置>侦测报警>人>报警类型——人
        name: 人
        object_size:
          desc: 设置>侦测报警>目标尺寸
          name: 目标尺寸
          text:
          - 取消
          - 目标尺寸
          - 保存
          type: navigation
        smart_detection:
          desc: 设置>侦测报警>人>智能侦测
          name: 智能侦测
          type: slider
        text:
        - 人
        - 报警类型「人」的相关设置
        - 目标尺寸
        - 智能侦测
        - '0'
        - '100'
        - 延时报警
        - 检测目标在报警区域内停留的时间超过设置时间将触发报警
        - '0'
        - '8'
        type: navigation
      smart_tracking:
        desc: 设置>侦测报警>智能追踪
        horizontal_tracking_range:
          desc: 设置>侦测报警>智能追踪>水平追踪范围
          left_side_text:
          - 取消
          - 左侧
          - 下一步
          - 设置最大左转角度
          name: 水平追踪范围
          right_side_text:
          - 上一步
          - 右侧
          - 保存
          - 设置最大右转角度
          text:
          - 水平追踪范围
          - 通过调整左侧和右侧最大旋转角度视图，来限制摄像头的自动水平追踪范围。
          - 设置
          type: navigation
        name: 智能追踪
        object_disappears:
          desc: 设置>侦测报警>智能追踪>目标消失
          name: 目标消失
          option_text:
          - 10 秒
          - 20 秒
          - 30 秒
          - 60 秒
          type: popup
        object_stops:
          desc: 设置>侦测报警>智能追踪>目标静止
          name: 目标静止
          option_text:
          - 10 秒
          - 20 秒
          - 30 秒
          - 60 秒
          type: popup
        text:
        - 追踪类型
        - 追踪方式
        - 水平追踪范围
        - 计划
        - 多久后结束追踪
        - 目标静止
        - 目标消失
        time_plan:
          desc: 设置>侦测报警>智能追踪>计划表
          name: 计划表
          text:
          - 取消
          - 计划
          - 保存
          - 报警
          - 该时间段内检测到移动事件时会进行录像。
          - 定时
          - 该时间段内会持续录像，并标识出报警录像。
          - 涂抹以选择录像时间
          type: navigation
        tracking_mode:
          desc: 设置>侦测报警>智能追踪>追踪方式
          name: 追踪方式
          option_text:
          - 数码
          - 数码优先
          - PT优先
          text:
          - 追踪方式
          - 数码
          - 数码优先
          - PT优先
          type: popup
        tracking_type:
          desc: 设置>侦测报警>智能追踪>追踪类型
          name: 追踪类型
          option_text:
          - 人
          - 车
          - 动物
          text:
          - 追踪类型
          - 保存
          - 全选
          - 人
          - 车
          - 动物
          type: popup
        type: switch
    name: 侦测报警
    text:
    - ''
    type: navigation
sub_name: ''
uid: 952700Y006ZP1IJ5
