device_list_name: yulong-test-sd7
ipc:
  display:
    desc: 设置>显示
    items:
      display:
        date:
          desc: 设置>显示>日期
          name: 日期
          options:
          - 隐藏
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          text:
          - 日期
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏
          type: popup
        day_and_night:
          black_and_white:
            desc: 白天和黑夜>黑白
            name: 黑白
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 黑白
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          day_color:
            desc: 白天和黑夜>白天彩色
            name: 白天彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 白天彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          desc: 白天和黑夜
          mode_switching:
            desc: 白天和黑夜>模式切换
            name: 模式切换
            options:
            - 黑白
            - 彩色
            - 自动
            - 日夜切换阈值
            text:
            - 模式切换
            - 黑白
            - 彩色
            - 自动
            - 光线较亮时自动显示彩色，较暗时自动显示黑白。
            - 日夜切换阈值
            - 白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：
            - 恢复默认值
            - '0'
            - '100'
            type: popup
          name: 白天和黑夜
          night_vision_color:
            desc: 白天和黑夜>夜视彩色
            name: 夜视彩色
            options:
            - 自动
            - 手动
            - 亮度
            - 暗部
            text:
            - 夜视彩色
            - 自动
            - 手动
            - 亮度
            - 恢复默认值
            - 暗部
            - '0'
            - '255'
            type: popup
          options:
          - 模式切换
          - 黑白
          - 白天彩色
          - 夜视彩色
          text:
          - 白天和黑夜
          - 模式切换
          - 高光/阴影调节
          - 黑白
          - 白天彩色
          - 夜视彩色
          type: popup

        device_name:
          desc: 设置>显示>设备名称
          name: 设备名称
          options:
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏
          text:
          - 设备名称
          - 左上
          - 中上
          - 右上
          - 左下
          - 中下
          - 右下
          - 隐藏
          type: popup
        horizontal_flip:
          desc: 设置>显示>水平翻转
          name: 水平翻转
          options:
          - switch_on
          - switch_off
          type: switch
        image_setting:
          anti_flicker:
            desc: 设置>显示>抗闪烁
            name: 抗闪烁
            options:
            - 50HZ
            - 60HZ
            - 其他
            - 关闭
            text:
            - 抗闪烁
            - 50HZ
            - 60HZ
            - 其他
            - 关闭
            type: popup
          brightness:
            name: 亮度
          desc: 设置>显示>图像设置
          name: 图像设置
          text:
          - 亮度
          - 抗闪烁
          - 调整摄像机的拍摄帧率，以减少受到画面中光源闪烁的影响。
          - '0'
          - '255'
          type: page
        motion_mark:
          desc: 设置>显示>移动标记
          name: 移动标记
          options:
          - switch-on
          - switch-off
          text:
          - 移动标记
          - 画面为清晰时，智能检测到移动事物将进行标记。
          type: switch

        options:
        - 垂直翻转
        - 水平翻转
        - 码流
        - 移动标记
        - 设备名称
        - 日期
        - 水印
        - 图像设置
        - 白天和黑夜
        - 遮盖区域
        text:
          - 垂直翻转
          - 水平翻转
          - 码流
          - 移动标记
          - 画面为清晰时，智能检测到移动事物将进行标记。
          - 设备名称
          - 日期
          - 水印
          - 图像设置
          - 白天和黑夜
          - 遮盖区域
        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'GC'
          mask_num: 4
        stream:
          clear:
            i_frame_interval:
              desc: 设置>显示>码流>码流>清晰>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x
            max_bit_rate:
              desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
              name: 最大码率(Kbps)
              options:
              - 4096(默认)
              - '5120'
              - '6144'
              - '7168'
              - '8192'
            resolution:
              options:
              - 3840*2160
            text:
            - I 帧间隔

          fluent:
            frame_rate:
              name: 帧率(FPS)
              options:
              - '20'
              - '18'
              - '16'
              - 15(默认)
              - '12'
              - '8'
              - '6'
              - '4'
            i_frame_interval:
              desc: 设置>显示>码流>码流>流畅>I 帧间隔
              name: I 帧间隔
              options:
              - 1x
              - 2x
              - 3x
              - 4x
            max_bit_rate:
              desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
              options:
              - '128'
              - '256'
              - '384'
              - '512'
              - '672'
              - 768(默认)
              - '1024'
              - '1228'
            resolution:
              desc: 设置>显示>码流>码流>流畅>分辨率
              name: 分辨率
              options:
              - 896*512
            text:
            - I 帧间隔

          frame_rate_mode:
            desc: 设置>显示>码流>码流>帧率控制
            name: 帧率控制
            support_mode: 'AB'

          text:
          - I 帧间隔
          - 帧率控制
          options:
          - 帧率控制

        vertical_flip: '垂直翻转(无需配置，有则保留无则删除)'
        watermark: '水印(无需配置，有则保留无则删除)'
uid: 952700Y006ZP1IJ5
