device_list_name: yulong-test-sd7
ipc:
  email_alerts:
    desc: 设置>邮件通知
    items:
      email_alerts:
        desc: 设置>邮件通知>邮件通知主页
        name: 邮件通知主页
        text:
        - 邮件通知
        - 测试
        - 检测到移动事件时，自动发送邮件提醒用户。
        - 计划
        - 可筛选报警类型或进行时间规划。
        - 邮件设置
        - 邮件内容
        - 邮箱间隔
        - 未收到邮件？
        type: page
      email_config:
        desc: 设置>邮件通知>邮件设置
        name: 邮件设置
        text:
        - 邮件设置
        - 清空
        - 发件邮箱
        - 收件邮箱
        - 添加邮箱
        type: navigation
      email_content:
        desc: 设置>邮件通知>邮件内容
        name: 邮件内容
        text:
        - 文字
        - 图片
        - 图片和文字
        - 视频和文字
        type: popup
      email_interval:
        desc: 设置>邮件通知>邮箱间隔
        name: 邮箱间隔
        text:
        - 30 秒
        - 1 分
        - 5 分
        - 10 分
        - 30 分
        type: popup
      email_not_received:
        desc: 设置>邮件通知>未收到邮件？
        name: 未收到邮件？
        text:
        - ''
        type: page
      plan:
        alarm:
          alarm_type:
            desc: 设置>邮件通知>计划主页>报警>报警类型
            name: 报警类型
            option_text:
            - 画面变动
            - 人
            - 车
            - 动物
            text:
            - 保存
            - 全选
            - 画面变动
            - 人
            - 车
            - 动物
            type: page
          desc: 设置>邮件通知>计划主页>报警
          name: 报警
          text:
          - 取消
          - 计划
          - 保存
          - 报警
          - 定时
          - 配置报警邮件（检测到报警事件时发送邮件通知）的触发类型和时间计划。
          - 报警类型
          type: tab
        desc: 设置>邮件通知>计划主页
        name: 计划
        text:
        - ''
        timed:
          desc: 设置>邮件通知>计划主页>定时
          name: 定时
          text:
          - 取消
          - 计划
          - 保存
          - 报警
          - 定时
          - 配置定时发送邮件的时间计划，启用的时间段内会按照一定的邮件间隔定时发送邮件。
          type: tab
        type: navigation
    name: 邮件通知
    text:
    - ''
    type: navigation
sub_name: ''
uid: 952700Y006ZP1IJ5
