device_list_name: "yulong Doorbell Battery"
uid: '952700Y0061K137Z'
sub_name: ""

ipc:
  push:
    name: '手机推送'
    desc: '设置>手机推送'
    type: 'switch'
    text:
      - ''

    items:
      push:
        name: '手机推送'
        desc: '设置>手机推送'
        type: 'switch'
        push_text:
          - '手机推送'
          - '测试'
          - '打开后，将会接收到移动事件与低电量通知。'
          - '此设备支持图文通知。了解更多'

      visitor_phone_remind:
        name: '访客电话提醒'
        desc: '设置>手机推送>访客电话提醒'
        type: 'switch'
        text:
          - '访客电话提醒'
          - '访客铃声'
          - '前往系统设置'
        option_text:
          - ''

      device_notify_ringtone:
        name: '设备通知铃声'
        desc: '设置>手机推送>设备通知铃声'
        type: 'switch'
        text:
          - '设备通知铃声'
          - '开启后，可为设备单独设置通知铃声。'
          - '报警铃声'
        alarm_ring:
          name: '报警铃声'
          desc: '设置>手机推送>设备通知铃声>报警铃声'
          type: 'popup'
          text:
            - ''
          option_text:
            - '强烈通知'
            - '重要通知'
            - '一般通知'

      schedule:
        name: '计划'
        desc: '设置>手机推送>计划'
        type: 'navigation'
        text:
          - '计划'
          - '可筛选报警类型或进行时间规划。'
        plan_main_text:
            - '取消'
            - '保存'
            - '配置推送的触发类型和时间计划。'
            - '报警类型'
        alarm_type:
          name: '报警类型'
          desc: '设置>手机推送>计划>报警类型'
          type: 'page'
          text:
            - '人'
            - '车'
            - '其他'
            - '访客'
            - '包裹'
          option_text:
            - '人'
            - '车'
            - '其他'
            - '访客'
            - '包裹'

