device_list_name: yulong-test-sd7
ipc:
  audio:
    desc: 设置>音频
    items:
      audio:
        desc: 设置>音频>音频主页
        device_volume_and_speaker_volume:
          desc: 设置>音频>设备音量
          name: 设备音量
          option_text:
          - ''
          text:
          - ''
          type: slider
        name: 音频
        noise_reduction:
          desc: 设置>音频>音频降噪
          name: 音频降噪
          option_text:
          - switch_on
          - switch_off
          text:
          - 降噪强度
          - 低
          - 高
          type: switch
        record_audio:
          desc: 设置>音频
          name: 录制声音
          option_text:
          - switch_on
          - switch_off
          text:
          - ''
          type: switch
        sound_test:
          desc: 设置>音频>试听
          name: 试听
          type: button
        text:
        - 音频
        - 录制声音
        - 关闭后，将不会录制声音到回放文件中
        - 设备音量
        - 报警音量和对讲音量
        - 试听
        - 音频降噪
        type: page
    name: 音频
    text:
    - ''
    type: navigation
sub_name: ''
uid: 952700Y006ZP1IJ5
