device_list_name: "yulong-test-sd7"
uid: '952700Y006ZP1IJ5'

ipc:
  push:
    name: '手机推送'
    desc: '设置>手机推送'
    type: 'switch'
    text:
      - '手机推送'
      - '测试'
      - '打开后，接收移动事件通知。'
      - '计划'
      - '可筛选报警类型或进行时间规划。'
      - '推送间隔'

    options:
      - '手机推送'
      - '计划'
      - '推送间隔'
    supported_test: '是否支持测试按钮，支持就保留该键，否则删除'

    items:

      schedule:
        name: '计划'
        desc: '设置>手机推送>计划'
        type: 'navigation'
        text:
          - '取消'
          - '计划'
          - '保存'
          - '配置推送的触发类型和时间计划。'
          - '报警类型'
        alarm_type:
          name: '报警类型'
          desc: '设置>手机推送>计划>报警类型'
          type: 'page'
          text:
            - '画面变动'
            - '人'
            - '车'
            - '动物'
          options:
            - '画面变动'
            - '人'
            - '车'
            - '动物'

        push_interval:
          name: '推送间隔'
          desc: '设置>手机推送>推送间隔'
          type: 'popup'
          text:
            - '20秒'
            - '30秒'
            - '60秒'
            - '120秒'
          options:
            - '20秒'
            - '30秒'
            - '60秒'
            - '120秒'

