device_list_name: "Reolink Altas PT Ultra"
uid: '952700Y100BF19GB'
sub_name: ""

ipc:
  camera_record:
    name: '摄像机录像'
    desc: '设置>摄像机录像'
    type: 'navigation'

    items:
      camera_record:
        name: '摄像机录像'
        desc: '设置>摄像机录像'
        type: 'navigation'
        alarm_recording_text:
          - '摄像机录像'
          - '报警录像'
          - '定时录像'
          - '报警录像计划'
          - '配置报警录像（检测到报警事件时触发录像）的触发类型和时间计划。'
          - '报警录像时长'
          - '触发事件停止后延后录制的时长'
          - '覆盖录像'
          - '打开时，当容量不足时，新生成的录像将覆盖最旧的录像。'
        timed_recording_text:
          - '摄像机录像'
          - '报警录像'
          - '定时录像'
          - '定时录像计划'
          - '配置持续录像的时间计划，启用的时间段会持续不间断录像。'

      alarm_recording_plan:
        name: '报警录像计划'
        desc: '设置>摄像机录像>报警录像>报警录像计划'
        type: 'navigation'
        text:
          - '取消'
          - '报警录像计划'
          - '保存'
          - '配置报警录像（检测到报警事件时触发录像）的触发类型和时间计划。'
          - '报警类型'

        alarm_type:
          desc: '设置>摄像机录像>报警录像>报警录像计划>报警类型'
          type: 'navigation'
          text:
            - '报警类型'
            - '保存'
            - '全选'
            - '画面变动'
            - '人'
            - '车'
            - '动物'
          option_text:
            - '画面变动'
            - '人'
            - '车'
            - '动物'

      overwrite_record:
        name: '覆盖录像'
        desc: '设置>摄像机录像>报警录像>覆盖录像'
        type: 'popup'
        text:
          - ''
        option_text:
          - ''

      timed_recording_plan:
        name: '定时录像计划'
        desc: '设置>摄像机录像>定时录像>定时录像计划'
        type: 'navigation'
        text:
          - '取消'
          - '定时录像计划'
          - '保存'
          - '配置持续录像的时间计划，启用的时间段会持续不间断录像。'

      smart_power_saving_mode:
        name: '智能省电模式'
        desc: '设置>摄像机录像>定时录像>智能省电模式'
        type: 'navigation'
        text:
          - '帧率(fps)'
          - '智能省电模式'
          - '不同电量下摄像机会以不同的设置进行定时录像，以延长使用时间。'
          - '智能省电模式关闭后，电量低于10%会停用定时录像'
          - '电量'
        frame_rate:
          name: '帧率'
          desc: '设置>摄像机录像>定时录像>智能省电模式>帧率'
          type: 'popup'
          text:
            - '帧率(fps)'
            - '低帧率续航更长，高帧率观看体验更佳'
            - '10'
            - '5(默认)'
            - '2'
            - '1'
          option_text:
            - '10'
            - '5(默认)'
            - '2'
            - '1'

