device_list_name: "Argus PT Ultra"
uid: '952700Y002PO3HHP'
sub_name: ""

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        name: '灯'
        desc: '设置>灯主页'
        type: 'page'
        text:
          - '状态灯'
          - '照明灯'

        floodlight:
          name: '照明灯'
          desc: '设置>灯>照明灯'
          type: 'navigation'
          text:
            - ''
          options:
            - ''

          light_off_mode:
            name: '关闭'
            desc: '设置>灯>照明灯>关闭'
            type: 'menu'

          auto_mode:
            name: '自动模式'
            desc: '设置>灯>照明灯>自动模式'
            type: 'menu'
            text:
              - ''

        status_lights:
          name: '状态灯'
          desc: '设置>灯>状态灯'
          type: 'navigation'
          text:
            - '状态灯'
            - '电池供电 WiFi 摄像头的状态 LED 有两种颜色：蓝色和红色。蓝色表示相机WiFi连接成功，红色表示WiFi连接失败'
            - '了解更多'
            - '关闭'
            - '状态灯将保持关闭'
            - '开启'
            - '状态灯将始终亮起'

          light_off_mode:
            name: '关闭'
            desc: '设置>灯>状态灯>关闭'
            type: 'menu'

          light_on_mode:
            name: '开启'
            desc: '设置>灯>状态灯>开启'
            type: 'menu'
