advanced_setting_page:
  name: '高级设置'
  desc: '高级设置页面-入口：设置>高级设置'
  type: 'page'
  items:
    user_management:
      name: '用户管理'
      desc: '设置>高级设置>用户管理'
      type: 'navigation'
      subpage:
        name: '用户管理'
        desc: '设置>高级设置>用户管理>用户管理页面'
        type: 'page'
    date_and_time:
      name: '日期和时间'
      desc: '设置>高级设置>日期和时间'
      type: 'navigation'
      subpage:
        name: '日期和时间'
        desc: '设置>高级设置>日期和时间>日期和时间页面'
        type: 'page'



