name: '设备信息'
key: 'device_info_page'
desc: '设置>设备信息'
type: 'page'
items:
  - name: '设备名称'
    key: 'device_name'
    desc: '设置>设备信息>设备名称'
    type: 'navigation'
    subpage:
      name: '修改名称'
      desc: '设置>设备信息>设备名称>修改名称'
      type: 'page'
  - name: '机型'
    key: 'model'
    desc: '设置>设备信息>机型'
    type: 'text'
  - name: 'UID'
    key: 'uid'
    desc: '设置>设备信息>UID'
    type: 'text'
  - name: '存储'
    key: 'storage'
    desc: '设置>设备信息>storage'
    type: 'navigation'
    subpage:
      name: '存储'
      desc: '设置>设备信息>存储'
      type: 'page'
  - name: '网络信息'
    key: 'network_info'
    desc: '设置>设备信息>网络信息'
    type: 'navigation'
    subpage:
      name: '网络状态'
      desc: '设置>设备信息>网络信息>网络状态'
      type: 'page'
      item:
        - name: 'IP 地址'
          key: 'ip_address'
          desc: '设置>设备信息>网络信息>网络状态>IP 地址'
          type: 'text'
        - name: '子网掩码'
          key: 'subnet_mask'
          desc: '设置>设备信息>网络信息>网络状态>子网掩码'
          type: 'text'
        - name: '网关'
          key: 'gateway'
          desc: '设置>设备信息>网络信息>网络状态>网关'
          type: 'text'
        - name: 'Mac 地址'
          key: 'mac_address'
          desc: '设置>设备信息>网络信息>网络状态>Mac 地址'
          type: 'text'
        - name: '首选DNS'
          key: 'preferred_dns'
          desc: '设置>设备信息>网络信息>网络状态>首选DNS'
          type: 'text'
        - name: '备用DNS'
          key: 'spare_dns'
          desc: '设置>设备信息>网络信息>网络状态>备用DNS'
          type: 'text'
        - name: '高级设置'
          key: 'advanced_setting'
          desc: '设置>设备信息>网络信息>网络状态>高级设置'
          type: 'navigation'
          subpage:
            name: '高级设置'
            desc: '设置>设备信息>网络信息>网络状态>高级设置>高级设置'
            type: 'page'
            items:
              - name: 'RTMP'
                desc: '设置>设备信息>网络信息>网络状态>高级设置>高级设置>RTMP'
                type: 'switch'
              - name: 'HTTP'
                desc: '设置>设备信息>网络信息>网络状态>高级设置>高级设置>HTTP'
                type: 'switch'
              - name: 'HTTPS'
                desc: '设置>设备信息>网络信息>网络状态>高级设置>高级设置>HTTPS'
                type: 'switch'
              - name: 'RTSP'
                desc: '设置>设备信息>网络信息>网络状态>高级设置>高级设置>RTSP'
                type: 'switch'
              - name: 'ONVIF'
                desc: '设置>设备信息>网络信息>网络状态>高级设置>高级设置>ONVIF'
                type: 'switch'
  - name: '移动信息'
    key: 'mobile_info'
    desc: '设置>设备信息>移动信息'
    type: 'navigation'
    subpage:
      name: '移动信息'
      desc: '设置>设备信息>移动信息>移动信息'
      type: 'page'
  - name: '设备升级'
    key: 'device_update'
    desc: '设置>设备信息>设备升级'
    type: 'navigation'
    subpage:
      name: '升级'
      desc: '设置>设备信息>设备升级>升级'
      type: 'page'
      items:
        - name: '自动升级'
          desc: '设置>设备信息>设备升级>升级>自动升级'
          type: 'switch'
        - name: '手动升级'
          desc: '设置>设备信息>设备升级>升级>手动升级'
          type: 'navigation'
          subpage:
            name: '升级'
            desc: '设置>设备信息>设备升级>升级>手动升级>升级'
            type: 'page'
  - name: '编译版本'
    key: 'build_version'
    desc: '设置>设备信息>编译版本'
    type: 'text'
  - name: '硬件版本'
    key: 'hardware_version'
    desc: '设置>设备信息>硬件版本'
    type: 'text'
  - name: '配置版本'
    key: 'config_version'
    desc: '设置>设备信息>配置版本'
    type: 'text'
  - name: '固件版本'
    key: 'firmware_version'
    desc: '设置>设备信息>固件版本'
    type: 'text'
  - name: '细节'
    key: 'detail'
    desc: '设置>设备信息>细节'
    type: 'text'






