name: '灯'
key: 'light_page'
desc: '设置>灯'
type: 'page'
items:
  - name: '状态灯'
    key: 'status_light'
    desc: '设置>灯>状态灯'
    type: 'navigation'
    subpage:
      name: '状态灯'
      desc: '设置>灯>状态灯>状态灯'
      type: 'page'
      items:
        name: '状态灯'
        desc: '设置>灯>状态灯>状态灯>状态灯'
        type: 'switch'
  - name: '红外灯'
    key: 'infrared_light'
    desc: '设置>灯>红外灯'
    type: 'navigation'
    subpage:
      name: '红外灯'
      desc: '设置>灯>红外灯>红外灯'
      type: 'page'
      items:
        - name: '自动'
          desc: '设置>灯>红外灯>红外灯>自动'
          type: 'text'
        - name: '保持关闭'
          desc: '设置>灯>红外灯>红外灯>保持关闭'
          type: 'text'
  - name: '照明灯'
    key: 'floodlight'
    desc: '设置>灯>照明灯'
    type: 'navigation'
    subpage:
      name: '照明灯'
      desc: '设置>灯>照明灯>照明灯'
      type: 'page'
      items:
        - name: '模式'
          type: 'navigation'
          desc: '设置>灯>照明灯>照明灯>模式'
          subpage:
            name: '模式'
            desc: '设置>灯>照明灯>照明灯>模式>模式'
            type: 'page'
            items:
              - name: '关'
                desc: '设置>灯>照明灯>照明灯>模式>模式>关'
                type: 'text'
              - name: '夜间智能模式'
                desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式'
                type: 'navigation'
                subpage:
                  - name: '侦测'
                    desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式>侦测'
                    type: 'page'
                    items:
                      - name: '人'
                        desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式>侦测>人'
                        type: 'text'
                      - name: '车'
                        desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式>侦测>车'
                        type: 'text'
                      - name: '动物'
                        desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式>侦测>动物'
                        type: 'text'
              - name: '定时模式'
                desc: '设置>灯>照明灯>照明灯>模式>模式>定时模式'
                type: 'text'
        - name: '根据环境明暗程度，调节照明灯亮度。'
          desc: '设置>灯>照明灯>照明灯>模式>滑块'
          type: 'slider'