status_light_page: &status_light_page_anchor
  name: '状态灯'
  desc: '设置>灯>状态灯>状态灯'
  type: 'page'
  items:
    status_light:
      name: '状态灯'
      desc: '设置>灯>状态灯>状态灯>状态灯'
      type: 'switch'


infrared_light_page: &infrared_light_page_anchor
  name: '红外灯'
  desc: '设置>灯>红外灯>红外灯'
  type: 'page'
  items:
    auto:
      name: '自动'
      desc: '设置>灯>红外灯>红外灯>自动'
      type: 'text'
    keep_closed:
      name: '保持关闭'
      desc: '设置>灯>红外灯>红外灯>保持关闭'
      type: 'text'


night_smart_mode_page: &night_smart_mode_page_anchor
  name: '侦测'
  desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式>侦测'
  type: 'page'
  items:
    person:
      name: '人'
      desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式>侦测>人'
      type: 'text'
    car:
      name: '车'
      desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式>侦测>车'
      type: 'text'
    animal:
      name: '动物'
      desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式>侦测>动物'
      type: 'text'
#    pet:
#      name: '宠物'
#      desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式>侦测>宠物'
#      type: 'text'

mode_page: &mode_page_anchor
  name: '模式'
  desc: '设置>灯>照明灯>照明灯>模式>模式'
  type: 'page'
  items:
    close:
      name: '关'
      desc: '设置>灯>照明灯>照明灯>模式>模式>关'
      type: 'text'
    night_smart_mode:
      name: '夜间智能模式'
      desc: '设置>灯>照明灯>照明灯>模式>模式>夜间智能模式'
      type: 'navigation'
      subpage: *night_smart_mode_page_anchor
    timer_mode:
      name: '定时模式'
      desc: '设置>灯>照明灯>照明灯>模式>模式>定时模式'
      type: 'text'


floodlight_page: &floodlight_page_anchor
  name: '照明灯'
  desc: '设置>灯>照明灯>照明灯'
  type: 'page'
  items:
    mode:
      name: '模式'
      type: 'navigation'
      desc: '设置>灯>照明灯>照明灯>模式'
      subpage: *mode_page_anchor
    adjust_brightness_slider:
      name: '根据环境明暗程度，调节照明灯亮度。'
      desc: '设置>灯>照明灯>照明灯>模式>滑块'
      type: 'slider'


light_page:
  name: '灯'
  desc: '设置>灯'
  type: 'page'
  items:
    status_light:
      name: '状态灯'
      desc: '设置>灯>状态灯'
      type: 'navigation'
      subpage: *status_light_page_anchor
    infrared_light:
      name: '红外灯'
      desc: '设置>灯>红外灯'
      type: 'navigation'
      subpage: *infrared_light_page_anchor
    floodlight:
      name: '照明灯'
      desc: '设置>灯>照明灯'
      type: 'navigation'
      subpage: *floodlight_page_anchor
