setting_page:
  name: '设置'
  desc: '单机设置页面'
  type: 'page'
  items:
      display:
        name: '显示'
        desc: '设置>显示'
        type: 'navigation'
      audio:
        name: '音频'
        desc: '设置>音频'
        type: 'navigation'
      light:
        name: '灯'
        desc: '设置>灯'
        type: 'navigation'
#      chime:
#        name: '叮咚'
#        desc: '设置>叮咚'
#        type: 'navigation'
#      pir_setting:
#        name: 'PIR 设置'
#        desc: '设置>PIR 设置'
#        type: 'navigation'
      detection_alarm:
        name: '侦测报警'
        desc: '设置>侦测报警'
        type: 'navigation'
      camera_recording:
        name: '摄像机录像'
        key: ''
        desc: '设置>摄像机录像'
        type: 'navigation'
      notification_push:
        name: '手机推送'
        desc: '设置>手机推送'
        type: 'navigation'
      email_alert:
        name: '邮件通知'
        desc: '设置>邮件通知'
        type: 'navigation'
      ftp:
        name: 'FTP'
        desc: '设置>FTP'
        type: 'navigation'
  #    siren:
  #      name: '鸣笛'
  #      desc: '设置>鸣笛'
  #      type: 'navigation'
      linked_device:
        name: '已联动的设备'
        desc: '设置>已联动的设备'
        type: 'navigation'
      share_camera:
        name: '分享摄像机'
        desc: '设置>分享摄像机'
        type: 'navigation'
      time_lapse:
        name: '延时摄影'
        desc: '设置>延时摄影'
        type: 'navigation'
  #    install_method:
  #      name: '安装方式'
  #      desc: '设置>安装方式'
  #      type: 'navigation'
      advanced_setting:
        name: '高级设置'
        desc: '设置>高级设置'
        type: 'navigation'



