device_list_name: "Reolink Duo 3 PoE"
uid: '952700Y1007SIHX8'
sub_name: ""

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        name: '灯'
        desc: '设置>灯主页'
        type: 'page'
        text:
          - '灯'
          - '红外灯'
          - '照明灯'

        infrared_light:
          name: '红外灯'
          desc: '设置>灯>红外灯'
          type: 'navigation'
          subpage:
            name: '红外灯'
            desc: '设置>灯>红外灯'
            type: 'page'
            text:
              - '红外灯'
              - '红外补光灯，能让你在夜晚或光线较暗时拍出更清晰的影像。'
              - '红外灯关闭'
              - '红外灯亮起'
              - '自动'
              - '光线较暗时自动开启，光线较亮时自动关闭。'
              - '保持关闭'
            options_text:
              - '自动'
              - '保持关闭'

        floodlight:
          name: '照明灯'
          desc: '设置>灯>照明灯'
          type: 'navigation'
          subpage:
            name: '照明灯'
            desc: '设置>灯>照明灯'
            type: 'page'

            light_off_mode:
              name: '关闭'
              desc: '设置>灯>照明灯>关闭'
              type: 'menu'
              text:
                - '白光灯'
                - '夜晚时开启照明灯画面呈彩色状态，拍摄效果更佳。'
                - '关闭'
                - '白光灯将保持关闭'
                - '定时模式'
                - '在预定的时间段内保持开启。'
                - '夜间智能模式'
                - '当相机在夜间检测到事件时自动打开。'

            timer_mode:
              name: '定时模式'
              desc: '设置>灯>照明灯>定时模式'
              type: 'menu'
              text:
                - '白光灯'
                - '夜晚时开启照明灯画面呈彩色状态，拍摄效果更佳。'
                - '关闭'
                - '白光灯将保持关闭'
                - '定时模式'
                - '在预定的时间段内保持开启。'
                - '开始时间'
                - '结束时间'
                - '夜间智能模式'
                - '当相机在夜间检测到事件时自动打开。'

            night_smart_mode:
              name: '夜间智能模式'
              desc: '设置>灯>照明灯>夜间智能模式'
              type: 'menu'
              text:
                - '白光灯'
                - '夜晚时开启照明灯画面呈彩色状态，拍摄效果更佳。'
                - '关闭'
                - '白光灯将保持关闭'
                - '定时模式'
                - '在预定的时间段内保持开启。'
                - '夜间智能模式'
                - '当相机在夜间检测到事件时自动打开。'
                - '侦测'

              detect_type:
                desc: '设置>灯>照明灯>夜间智能模式>侦测'
                type: 'navigation'
                text:
                  - '报警类型'
                  - '保存'
                  - '全选'
                  - '画面变动'
                  - '人'
                  - '车'
                  - '动物'
                option_text:
                  - '人'
                  - '车'
                  - '动物'
