# 远程配置主页能力集提取id：
remote_setting: 'ReoTitle'

# 远程配置>WiFi主页：
WiFi_setting: ''

# 远程配置>display主页：
display_setting: ''

# 左上角通用返回上一页按钮：
back: '//*[@resource-id="HeaderLeft-ReoIcon"]'

# 选择用例执行时，测试单机或hub或nvr，并填写对应的nvr和hub名称：
access_mode: 'ipc'
nvr_name: 'Reolink home hub pro'
hub_name: 'Reolink-NVR'