devices:
  device1:
    name: "Reolink TrackMix WiFi001"
    uid: "952700Y006ZP1IJ5"
    model_type: "Reolink TrackMix WiFi"
    pages:
      sub_page_wifi:
        expected_page_title: "Wi-Fi"
        expected_texts:
          - "Wi-Fi 频段偏好"
          - "连接同一Wi-Fi的哪种频段"
          - "Wi-Fi测速"
          - "检测局域网设备当前的Wi-Fi信号强度"
          - "当前Wi-Fi"
          - "未连接"
          - "切换Wi-Fi"
          - "添加其他网络"
        excluded_texts:
          - "自动"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.TextView"
          index: "0"
          enabled: "true"
          text: { not_equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/device_name_tv" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeStaticText"
          index: "0"
          accessible: { not_equal: "false" }
      sub_page_wifi_band_preference:
        page_title: "Wi-Fi 频段偏好"
        expected_texts:
          - "家庭"
          - "办公"
        excluded_texts:
          - "取消"
          - "继续"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.TextView"
          index: "0"
          enabled: "true"
          text: { not_equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/usage_option_tv" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeStaticText"
          index: "0"
          accessible: { not_equal: "false" }
      sub_page_wifi_speed_test:
        page_title: "Wi-Fi Speed Test"
        expected_texts:
          - "Wi-Fi"
          - "以太网"
        excluded_texts:
          - "返回"
          - "下一步"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.TextView"
          index: "0"
          enabled: "true"
          text: { not_equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/network_option_tv" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeStaticText"
          index: "0"
          accessible: { not_equal: "false" }
      page_access_device_login:
        page_title: "访问设备登录"
        expected_texts:
          - "用户名"
          - "密码"
        excluded_texts:
          - "登录"
          - "忘记密码"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.EditText"
          index: "0"
          enabled: "true"
          text: { equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/username_et" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeTextField"
          index: "0"
          accessible: { not_equal: "false" }
  device2:
    name: "FE-W"
    uid: "952700Y006ZP1IJ2"
    model_type: "FE-W"
    pages:
      page_remote_setting:
        page_title: "远程设置"
        expected_texts:
          - "FTP"
          - "Wi-Fi"
          - "侦测报警"
          - "分享摄像机"
        excluded_texts:
          - "开"
          - "关"
          - "设置"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.TextView"
          index: "0"
          enabled: "true"
          text: { not_equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/device_name_tv" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeStaticText"
          index: "0"
          accessible: { not_equal: "false" }
      page_choose_device_usage:
        page_title: "选择设备使用"
        expected_texts:
          - "家庭"
          - "办公"
        excluded_texts:
          - "取消"
          - "继续"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.TextView"
          index: "0"
          enabled: "true"
          text: { not_equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/usage_option_tv" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeStaticText"
          index: "0"
          accessible: { not_equal: "false" }
      page_choose_network_access_method:
        page_title: "选择网络访问方式"
        expected_texts:
          - "Wi-Fi"
          - "以太网"
        excluded_texts:
          - "返回"
          - "下一步"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.TextView"
          index: "0"
          enabled: "true"
          text: { not_equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/network_option_tv" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeStaticText"
          index: "0"
          accessible: { not_equal: "false" }
      page_access_device_login:
        page_title: "访问设备登录"
        expected_texts:
          - "用户名"
          - "密码"
        excluded_texts:
          - "登录"
          - "忘记密码"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.EditText"
          index: "0"
          enabled: "true"
          text: { equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/username_et" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeTextField"
          index: "0"
          accessible: { not_equal: "false" }
  device3:
    name: "small Home Hub"
    uid: "952700Y006ZP1IJ3"
    model_type: "Reolink Home Hub"
    pages:
      page_remote_setting:
        page_title: "远程设置"
        expected_texts:
          - "FTP"
          - "Wi-Fi"
          - "侦测报警"
          - "分享摄像机"
        excluded_texts:
          - "开"
          - "关"
          - "设置"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.TextView"
          index: "0"
          enabled: "true"
          text: { not_equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/device_name_tv" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeStaticText"
          index: "0"
          accessible: { not_equal: "false" }
      page_choose_device_usage:
        page_title: "选择设备使用"
        expected_texts:
          - "家庭"
          - "办公"
        excluded_texts:
          - "取消"
          - "继续"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.TextView"
          index: "0"
          enabled: "true"
          text: { not_equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/usage_option_tv" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeStaticText"
          index: "0"
          accessible: { not_equal: "false" }
      page_choose_network_access_method:
        page_title: "选择网络访问方式"
        expected_texts:
          - "Wi-Fi"
          - "以太网"
        excluded_texts:
          - "返回"
          - "下一步"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.TextView"
          index: "0"
          enabled: "true"
          text: { not_equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/network_option_tv" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeStaticText"
          index: "0"
          accessible: { not_equal: "false" }
      page_access_device_login:
        page_title: "访问设备登录"
        expected_texts:
          - "用户名"
          - "密码"
        excluded_texts:
          - "登录"
          - "忘记密码"
        xml_az_parse_conditions:
          package: "com.mcu.reolink"
          class: "android.widget.EditText"
          index: "0"
          enabled: "true"
          text: { equal: "" }
          resource-id: { not_equal: "com.mcu.reolink:id/username_et" }
        xml_ios_parse_conditions:
          type: "XCUIElementTypeTextField"
          index: "0"
          accessible: { not_equal: "false" }