device_list_name: 'SD78-y184'
uid: '952700Y101E7Y184'
sub_name: ''

ipc:
  pre_recording:
    name: '预录模式'
    desc: '设置>预录模式'
    type: 'page'
    text:
      - ''

    items:
      pre_recording:
        name: '预录模式'
        desc: '设置>预录模式主页'
        type: 'page'
        text:
          - '预录模式'
          - '预录报警事件发生前的录像，但会增加能耗。了解更多...'
          - '停止预录电量'
          - '设备电量低于设定电量时关闭预录模式。'
          - '10%'
          - '80%'
          - '帧率(fps)'
          - '计划'

        FPS:
          name: '帧率(fps)'
          desc: '设置>预录模式主页>帧率(fps)'
          type: 'page'
          text:
            - '帧率(fps)'
            - '低帧率续航更长，高帧率观看体验更佳'
            - '10'
            - '5(默认)'
            - '2'
            - '1'
          options_text:
            - '1'
            - '10'
            - '5(默认)'
            - '2'

        pre_record_plan:
          name: '计划'
          desc: '设置>预录模式主页>计划'
          type: 'page'
          text:
            - '取消'
            - '计划'
            - '保存'
            - '始终开启'
            - '自定义'
            - '自定义计划'
            - '+新增计划'
            - '无计划'
          options_text:
            - '始终开启'
            - '自定义'

        add_new_plan:
          name: '新增计划'
          desc: '设置>预录模式主页>计划>新增计划'
          type: 'page'
          text:
            - '取消'
            - '新增计划'
            - '完成'
            - '开始时间'
            - '00:00'
            - '结束时间'
            - '23:59'
            - '重复'
            - '每天'
            - '每周'
            - '周日'
            - '周一'
            - '周二'
            - '周三'
            - '周四'
            - '周五'
            - '周六'