device_list_name: "Argus 2"
uid: '952700014C9A7UNU'

ipc:
  display:
    name: '显示'
    desc: '设置>显示'
    type: 'navigation'

    items:
      display:
        name: '显示'
        desc: '设置>显示'
        type: 'navigation'
        text:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '设备名称'
          - '日期'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'
        options:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '设备名称'
          - '日期'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'

        vertical_flip: '垂直翻转'
        horizontal_flip: '水平翻转'


        stream:
          text:
            - ''
          options:
            - ''

          clear:
            text:
              - ''

            resolution:
              name: '分辨率'
              options:
                - '1920*1080'
                - '1280*720'

            frame_rate:
              name: '帧率(FPS)'
              options:
                - '15(默认)'
                - '10'
                - '5'
                - '2'

            max_bit_rate:
              name: '最大码率(kbps)'
              options:
                - '256'
                - '512'
                - '768'
                - '1024'
                - '1536(默认)'
                - '2048'

          fluent:
            name: '流畅'
            text:
              - ''

            resolution:
              name: '分辨率'
              options:
                - '640*360'

            frame_rate:
              name: '帧率(FPS)'
              options:
                - '15'
                - '10'
                - '5(默认)'
                - '2'

            max_bit_rate:
              name: '最大码率(kbps)'
              options:
                - '64'
                - '128'
                - '160'
                - '192'
                - '256'
                - '384'
                - '512'

        device_name: '设备名称'

        date: '日期'

        image_setting:
          name: '图像设置(只需要确认亮度同步/hdr/夜视通透模式/抗闪烁)'
          brightness: '亮度'
#          contrast: '对比度'
#          saturation: '饱和度'
#          sharpness: '锐度'
          brightness_sync: false
          hdr: false
          night_transparent_vision: false
          anti_flicker: true

        day_and_night:
          name: '白天和黑夜'
          desc: '白天和黑夜'
          type: 'popup'
          text:
            - '白天和黑夜'
            - '模式切换'
          options:
            - '模式切换'

          mode_switching:
            name: '模式切换'
            desc: '白天和黑夜>模式切换'
            type: 'popup'
            text:
              - '模式切换'
              - '黑白'
              - '彩色'
              - '自动'
              - '光线较亮时自动显示彩色，较暗时自动显示黑白。'
              - '恢复默认值'
              - '0'
              - '100'
            options:
              - '黑白'
              - '彩色'
              - '自动'

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 4
