

google_assistant_page: &google_assistant_page_anchor
  name: 'Google Assistant'
  desc: '设置>叮咚>Google Assistant>Google Assistant'
  type: 'page'


alexa_page: &alexa_page_anchor
  name: 'Alex'
  desc: '计划页面-入口：设置>叮咚>Alex>Alex'
  type: 'page'


chime_page:
  name: '叮咚'
  key: 'chime_page'
  desc: '叮咚页面-入口：设置>叮咚'
  type: 'page'
  items:
    reolink_chime:
      name: 'Reolink 叮咚'
      desc: '设置>叮咚>Reolink 叮咚'
      type: 'navigation'
    google_assistant:
      name: 'Google Assistant'
      desc: '设置>叮咚>Google Assistant'
      type: 'navigation'
      subpage: *google_assistant_page_anchor
    alexa:
      name: 'Alexa'
      desc: '设置>叮咚>Alexa'
      type: 'navigation'
      subpage: *alexa_page_anchor

