advanced_setting_page: &id001
  desc: 设置>显示>高级设置>高级设置
  items:
    threshold:
      desc: 设置>显示>高级设置>阈值
      name: 阈值
      type: popup
  name: 高级设置
  type: page
bright_shade_setting_page: &id002
  desc: 设置>显示>明暗设置>明暗设置
  items:
    black_and_white:
      desc: 设置>显示>明暗设置>明暗设置>黑白
      name: 黑白
      type: switch
    daytime_colorful:
      desc: 设置>显示>明暗设置>明暗设置>白天彩色
      name: 白天彩色
      type: switch
  name: 明暗设置
  type: page
clear_page: &id003
  desc: 设置>显示>码流>码流>清晰
  items:
    encoding_format:
      desc: 设置>显示>码流>码流>清晰>编码格式
      name: 编码格式
      options:
      - H.264
      - H.265
      type: popup
    frame_rate:
      desc: 设置>显示>码流>码流>清晰>帧率(FPS)
      name: 帧率(FPS)
      options:
      - 30(默认)
      - '25'
      - '22'
      - '20'
      - '18'
      - '16'
      - '15'
      - '12'
      - '10'
      - '8'
      - '6'
      - '4'
      - '2'
      type: popup
    max_bit_rate:
      desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
      name: 最大码率(Kbps)
      options:
      - '1536'
      - '2048'
      - '3072'
      - '4096'
      - '5120'
      - 6144(默认)
      - '7168'
      - '8192'
      type: popup
    resolution:
      desc: 设置>显示>码流>码流>清晰>分辨率
      name: 分辨率
      options:
      - 2560*1920
      - 2560*1440
      - 2048*1536
      - 2304*1296
      type: popup
  name: 清晰
  type: page
display_page:
  desc: 设置>显示
  items:
    advanced_setting:
      desc: 设置>显示>高级设置
      key: ''
      name: 高级设置
      subpage: *id001
      type: navigation
    anti_flicker:
      desc: 设置>显示>抗闪烁
      name: 抗闪烁
      options:
      - 50HZ
      - 60HZ
      - 其他
      - 关闭
      type: popup
    bright_shade_setting:
      desc: 设置>显示>明暗设置
      key: ''
      name: 明暗设置
      subpage: *id002
      type: navigation
    brightness:
      desc: 设置>显示>亮度
      name: 亮度
      type: slider
    date:
      desc: 设置>显示>日期
      key: ''
      name: 日期
      options:
      - 左上
      - 中上
      - 右上
      - 左下
      - 中下
      - 右下
      - 隐藏
      type: popup
    day_and_night:
      desc: 设置>显示>白天和黑夜
      name: 白天和黑夜
      options:
      - 黑白
      - 彩色
      - 自动
      type: popup
    device_name:
      desc: 设置>显示>设备名称
      name: 设备名称
      options:
      - 左上
      - 中上
      - 右上
      - 左下
      - 中下
      - 右下
      - 隐藏
      type: popup
    flip_horizontal:
      desc: 设置>显示>水平翻转
      name: 水平翻转
      type: switch
    flip_vertical:
      desc: 设置>显示>垂直翻转
      name: 垂直翻转
      type: switch
    private_mark:
      desc: 设置>显示>遮盖区域
      name: 遮盖区域
      subpage: &id005
        desc: 设置>显示>遮盖区域>遮盖区域
        name: 遮盖区域
        type: page
      type: navigation
    stream:
      desc: 设置>显示>码流
      name: 码流
      subpage: &id006
        desc: 设置>显示>码流>码流
        items:
          bit_rate_mode:
            desc: 设置>显示>码流>码流>码率模式
            name: 码率模式
            options:
            - 固定码率
            - 动态码率
            type: popup
          clear:
            desc: 设置>显示>码流>码流>清晰
            key: clear
            name: 清晰
            subpage: *id003
            type: navigation
          fluent:
            desc: 设置>显示>码流>码流>流畅
            key: fluent
            name: 流畅
            subpage: &id004
              desc: 设置>显示>码流>码流>流畅
              items:
                frame_rate:
                  desc: 设置>显示>码流>码流>流畅>帧率(FPS)
                  name: 帧率(FPS)
                  options:
                  - '15'
                  - 10(默认)
                  - '7'
                  - '4'
                  type: popup
                max_bit_rate:
                  desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
                  name: 最大码率(Kbps)
                  options:
                  - '64'
                  - '128'
                  - '160'
                  - '192'
                  - 256(默认)
                  - '384'
                  - '512'
                  type: popup
                resolution:
                  desc: 设置>显示>码流>码流>流畅>分辨率
                  name: 分辨率
                  options:
                  - 640*480
                  type: popup
              name: 流畅
              type: page
            type: navigation
          frame_rate_mode:
            desc: 设置>显示>码流>码流>帧率控制
            name: 帧率控制
            options:
            - 自动
            - 恒定
            type: popup
        name: 码流
      type: navigation
    watermark:
      desc: 设置>显示>水印
      key: ''
      name: 水印
      type: switch
  key: display_page
  name: 显示
  type: page
fluent_page: *id004
private_mark_page: *id005
stream_page: *id006
