device_list_name: yulong-RLC-510A
hub:
  display:
    desc: 设置>显示
    items:
      advanced_setting:
        desc: 设置>显示>高级设置
        name: 高级设置
        subpage:
          desc: 设置>显示>高级设置>高级设置
          name: 高级设置
          text:
          - 高级设置
          - 阈值
          - 自动切换日夜模式
          threshold:
            desc: 设置>显示>高级设置>阈值
            name: 阈值
            text:
            - 日夜切换阈值
            - 白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：
            - 恢复默认值
            - 取消
            - 确定
            type: popup
          type: page
        type: navigation
      anti_flicker:
        desc: 设置>显示>抗闪烁
        name: 抗闪烁
        options:
        - 50HZ
        - 60HZ
        - 其他
        - 关闭
        - 取消
        text:
        - 抗闪烁
        type: popup
      bright_shade_setting:
        desc: 设置>显示>明暗设置
        name: 明暗设置
        subpage:
          black_and_white:
            desc: 设置>显示>明暗设置>明暗设置>黑白
            name: 黑白
            type: switch
          color_day:
            desc: 设置>显示>明暗设置>明暗设置>白天彩色
            name: 白天彩色
            type: switch
          desc: 设置>显示>明暗设置>明暗设置
          name: 明暗设置
          night_vision_color:
            desc: 设置>显示>明暗设置>明暗设置>夜视彩色
            name: 夜视彩色
            type: switch
          text:
          - 明暗设置
          - 白天彩色
          - 自动
          - 黑白
          - 夜视彩色
          type: page
        type: navigation
      brightness:
        desc: 设置>显示>亮度
        name: 亮度
        options:
        - ''
        - ''
        - ''
        type: slider
      date:
        desc: 设置>显示>日期
        name: 日期
        options:
        - 左上
        - 中上
        - 右上
        - 左下
        - 中下
        - 右下
        - 隐藏
        - 取消
        type: popup
      day_and_night:
        desc: 白天和黑夜
        name: 白天和黑夜
        options:
        - 黑白
        - 彩色
        - 自动
        - 取消
        text:
        - 光线较亮时自动显示彩色，较暗时自动显示黑白。
        type: popup
      device_name:
        desc: 设置>显示>设备名称
        name: 设备名称
        options:
        - 左上
        - 中上
        - 右上
        - 左下
        - 中下
        - 右下
        - 隐藏
        - 取消
        type: popup
      horizontal_flip:
        desc: 设置>显示>水平翻转
        name: 水平翻转
        options:
        - switch_on
        - switch_off
        type: switch
      private_mark:
        desc: 设置>显示>遮盖区域
        name: 遮盖区域
        subpage:
          desc: 设置>显示>遮盖区域>遮盖区域
          name: 遮盖区域
          text:
          - 取消
          - 遮盖区域
          - 保存
          - 广角画面
          - 长焦画面
          - 清空当前通道
          - 在画面中通过手指滑动添加黑色遮挡区域，监控视频中的遮挡区域将不可见，最多可遮挡4个区域。
          type: page
        type: navigation
      stream:
        desc: 设置>显示>码流
        name: 码流
        subpage:
          clear:
            desc: 设置>显示>码流>码流>清晰
            name: 清晰
            subpage:
              desc: 设置>显示>码流>码流>清晰
              frame_rate:
                desc: 设置>显示>码流>码流>清晰>帧率(FPS)
                name: 帧率(FPS)
                options:
                - '25'
                - '22'
                - '20'
                - '18'
                - '16'
                - 15(默认)
                - '12'
                - '10'
                - 取消
                text:
                - 帧率(FPS)
                - 每秒钟的帧数，越高画面越流畅
                type: popup
              max_bit_rate:
                desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
                options:
                - 4096(默认)
                - '5120'
                - '6144'
                - '7168'
                - '8192'
                - 取消
                text:
                - 最大码率(Kbps)
                - 相同的分辨率、帧率下，码率越大画质越好，网络要求也越高
                type: popup
              name: 清晰
              resolution:
                desc: 设置>显示>码流>码流>清晰>分辨率
                name: 分辨率
                options:
                - 3840*2160
                - 取消
                text:
                - 分辨率
                - 越高视频越清晰
                - 取消
                type: popup
              text:
              - 取消
              - 清晰
              - 保存
              - 分辨率
              - 帧率(FPS)
              - 最大码率(Kbps)
              type: page
            type: navigation
          desc: 设置>显示>码流>码流
          fluent:
            desc: 设置>显示>码流>码流>流畅
            name: 流畅
            subpage:
              desc: 设置>显示>码流>码流>流畅
              frame_rate:
                desc: 设置>显示>码流>码流>流畅>帧率(FPS)
                name: 帧率(FPS)
                options:
                - '20'
                - '18'
                - '16'
                - 15(默认)
                - '12'
                - '8'
                - '6'
                - '4'
                - 取消
                text:
                - 帧率(FPS)
                - 每秒钟的帧数，越高画面越流畅
                type: popup
              max_bit_rate:
                desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
                options:
                - '128'
                - '256'
                - '384'
                - '512'
                - '672'
                - 768(默认)
                - '1024'
                - '1228'
                - 取消
                text:
                - 最大码率(Kbps)
                - 相同的分辨率、帧率下，码率越大画质越好，网络要求也越高
                type: popup
              name: 流畅
              resolution:
                desc: 设置>显示>码流>码流>流畅>分辨率
                name: 分辨率
                options:
                - 896*512
                - 取消
                text:
                - 分辨率
                - 越高视频越清晰
                - 取消
                type: popup
              type: page
            type: navigation
          frame_rate_mode:
            desc: 设置>显示>码流>码流>帧率控制
            name: 帧率控制
            options:
            - 自动
            - 恒定
            - 取消
            text:
            - 帧率控制
            - 自动
            - 可变帧率，自动调节帧率来保持画质（不适用有快速运动的物体）。
            - 恒定
            - 恒定帧率，流畅优先。
            - 取消
            type: popup
          name: 码流
          text:
          - 码流
          - 清晰
          - 分辨率
          - 帧率(FPS)
          - 最大码率(Kbps)
          - 流畅
          - 帧率控制
          type: navigation
        type: navigation
      vertical_flip:
        desc: 设置>显示>垂直翻转
        name: 垂直翻转
        options:
        - switch_on
        - switch_off
        type: switch
      watermark:
        desc: 设置>显示>水印
        name: 水印
        options:
        - switch_on
        - switch_off
        type: switch
    name: 显示
    type: navigation
ipc:
  display:
    desc: 设置>显示
    items:
      advanced_setting:
        desc: 设置>显示>高级设置
        name: 高级设置
        subpage:
          desc: 设置>显示>高级设置>高级设置
          name: 高级设置
          text:
          - 高级设置
          - 阈值
          - 自动切换日夜模式
          threshold:
            desc: 设置>显示>高级设置>阈值
            name: 阈值
            text:
            - 日夜切换阈值
            - 白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：
            - 恢复默认值
            - 取消
            - 确定
            type: popup
          type: page
        type: navigation
      anti_flicker:
        desc: 设置>显示>抗闪烁
        name: 抗闪烁
        options:
        - 50HZ
        - 60HZ
        - 其他
        - 关闭
        - 取消
        text:
        - 抗闪烁
        type: popup
      bright_shade_setting:
        desc: 设置>显示>明暗设置
        name: 明暗设置
        subpage:
          black_and_white:
            desc: 设置>显示>明暗设置>明暗设置>黑白
            name: 黑白
            type: switch
          color_day:
            desc: 设置>显示>明暗设置>明暗设置>白天彩色
            name: 白天彩色
            type: switch
          desc: 设置>显示>明暗设置>明暗设置
          name: 明暗设置
          night_vision_color:
            desc: 设置>显示>明暗设置>明暗设置>夜视彩色
            name: 夜视彩色
            type: switch
          text:
          - 明暗设置
          - 白天彩色
          - 自动
          - 黑白
          - 夜视彩色
          type: page
        type: navigation
      brightness:
        desc: 设置>显示>亮度
        name: 亮度
        options:
        - ''
        - ''
        - ''
        type: slider
      date:
        desc: 设置>显示>日期
        name: 日期
        options:
        - 左上
        - 中上
        - 右上
        - 左下
        - 中下
        - 右下
        - 隐藏
        - 取消
        type: popup
      day_and_night:
        desc: 白天和黑夜
        name: 白天和黑夜
        options:
        - 黑白
        - 彩色
        - 自动
        - 取消
        text:
        - 光线较亮时自动显示彩色，较暗时自动显示黑白。
        type: popup
      device_name:
        desc: 设置>显示>设备名称
        name: 设备名称
        options:
        - 左上
        - 中上
        - 右上
        - 左下
        - 中下
        - 右下
        - 隐藏
        - 取消
        type: popup
      horizontal_flip:
        desc: 设置>显示>水平翻转
        name: 水平翻转
        options:
        - switch_on
        - switch_off
        type: switch
      private_mark:
        desc: 设置>显示>遮盖区域
        name: 遮盖区域
        subpage:
          desc: 设置>显示>遮盖区域>遮盖区域
          name: 遮盖区域
          text:
          - 取消
          - 遮盖区域
          - 保存
          - 广角画面
          - 长焦画面
          - 清空当前通道
          - 在画面中通过手指滑动添加黑色遮挡区域，监控视频中的遮挡区域将不可见，最多可遮挡4个区域。
          type: page
        type: navigation
      stream:
        desc: 设置>显示>码流
        name: 码流
        subpage:
          clear:
            desc: 设置>显示>码流>码流>清晰
            name: 清晰
            subpage:
              desc: 设置>显示>码流>码流>清晰
              frame_rate:
                desc: 设置>显示>码流>码流>清晰>帧率(FPS)
                name: 帧率(FPS)
                options:
                - '25'
                - '22'
                - '20'
                - '18'
                - '16'
                - 15(默认)
                - '12'
                - '10'
                - 取消
                text:
                - 帧率(FPS)
                - 每秒钟的帧数，越高画面越流畅
                type: popup
              max_bit_rate:
                desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
                options:
                - 4096(默认)
                - '5120'
                - '6144'
                - '7168'
                - '8192'
                - 取消
                text:
                - 最大码率(Kbps)
                - 相同的分辨率、帧率下，码率越大画质越好，网络要求也越高
                type: popup
              name: 清晰
              resolution:
                desc: 设置>显示>码流>码流>清晰>分辨率
                name: 分辨率
                options:
                - 3840*2160
                - 取消
                text:
                - 分辨率
                - 越高视频越清晰
                - 取消
                type: popup
              text:
              - 取消
              - 清晰
              - 保存
              - 分辨率
              - 帧率(FPS)
              - 最大码率(Kbps)
              type: page
            type: navigation
          desc: 设置>显示>码流>码流
          fluent:
            desc: 设置>显示>码流>码流>流畅
            name: 流畅
            subpage:
              desc: 设置>显示>码流>码流>流畅
              frame_rate:
                desc: 设置>显示>码流>码流>流畅>帧率(FPS)
                name: 帧率(FPS)
                options:
                - '20'
                - '18'
                - '16'
                - 15(默认)
                - '12'
                - '8'
                - '6'
                - '4'
                - 取消
                text:
                - 帧率(FPS)
                - 每秒钟的帧数，越高画面越流畅
                type: popup
              max_bit_rate:
                desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
                options:
                - '128'
                - '256'
                - '384'
                - '512'
                - '672'
                - 768(默认)
                - '1024'
                - '1228'
                - 取消
                text:
                - 最大码率(Kbps)
                - 相同的分辨率、帧率下，码率越大画质越好，网络要求也越高
                type: popup
              name: 流畅
              resolution:
                desc: 设置>显示>码流>码流>流畅>分辨率
                name: 分辨率
                options:
                - 896*512
                - 取消
                text:
                - 分辨率
                - 越高视频越清晰
                - 取消
                type: popup
              type: page
            type: navigation
          frame_rate_mode:
            desc: 设置>显示>码流>码流>帧率控制
            name: 帧率控制
            options:
            - 自动
            - 恒定
            - 取消
            text:
            - 帧率控制
            - 自动
            - 可变帧率，自动调节帧率来保持画质（不适用有快速运动的物体）。
            - 恒定
            - 恒定帧率，流畅优先。
            - 取消
            type: popup
          name: 码流
          text:
          - 码流
          - 清晰
          - 分辨率
          - 帧率(FPS)
          - 最大码率(Kbps)
          - 流畅
          - 帧率控制
          type: navigation
        type: navigation
      vertical_flip:
        desc: 设置>显示>垂直翻转
        name: 垂直翻转
        options:
        - switch_on
        - switch_off
        type: switch
      watermark:
        desc: 设置>显示>水印
        name: 水印
        options:
        - switch_on
        - switch_off
        type: switch
    name: 显示
    type: navigation
nvr:
  display:
    desc: 设置>显示
    items:
      advanced_setting:
        desc: 设置>显示>高级设置
        name: 高级设置
        subpage:
          desc: 设置>显示>高级设置>高级设置
          name: 高级设置
          text:
          - 高级设置
          - 阈值
          - 自动切换日夜模式
          threshold:
            desc: 设置>显示>高级设置>阈值
            name: 阈值
            text:
            - 日夜切换阈值
            - 白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：
            - 恢复默认值
            - 取消
            - 确定
            type: popup
          type: page
        type: navigation
      anti_flicker:
        desc: 设置>显示>抗闪烁
        name: 抗闪烁
        options:
        - 50HZ
        - 60HZ
        - 其他
        - 关闭
        - 取消
        text:
        - 抗闪烁
        type: popup
      bright_shade_setting:
        desc: 设置>显示>明暗设置
        name: 明暗设置
        subpage:
          black_and_white:
            desc: 设置>显示>明暗设置>明暗设置>黑白
            name: 黑白
            type: switch
          color_day:
            desc: 设置>显示>明暗设置>明暗设置>白天彩色
            name: 白天彩色
            type: switch
          desc: 设置>显示>明暗设置>明暗设置
          name: 明暗设置
          night_vision_color:
            desc: 设置>显示>明暗设置>明暗设置>夜视彩色
            name: 夜视彩色
            type: switch
          text:
          - 明暗设置
          - 白天彩色
          - 自动
          - 黑白
          - 夜视彩色
          type: page
        type: navigation
      brightness:
        desc: 设置>显示>亮度
        name: 亮度
        options:
        - ''
        - ''
        - ''
        type: slider
      date:
        desc: 设置>显示>日期
        name: 日期
        options:
        - 左上
        - 中上
        - 右上
        - 左下
        - 中下
        - 右下
        - 隐藏
        - 取消
        type: popup
      day_and_night:
        desc: 白天和黑夜
        name: 白天和黑夜
        options:
        - 黑白
        - 彩色
        - 自动
        - 取消
        text:
        - 光线较亮时自动显示彩色，较暗时自动显示黑白。
        type: popup
      device_name:
        desc: 设置>显示>设备名称
        name: 设备名称
        options:
        - 左上
        - 中上
        - 右上
        - 左下
        - 中下
        - 右下
        - 隐藏
        - 取消
        type: popup
      horizontal_flip:
        desc: 设置>显示>水平翻转
        name: 水平翻转
        options:
        - switch_on
        - switch_off
        type: switch
      private_mark:
        desc: 设置>显示>遮盖区域
        name: 遮盖区域
        subpage:
          desc: 设置>显示>遮盖区域>遮盖区域
          name: 遮盖区域
          text:
          - 取消
          - 遮盖区域
          - 保存
          - 广角画面
          - 长焦画面
          - 清空当前通道
          - 在画面中通过手指滑动添加黑色遮挡区域，监控视频中的遮挡区域将不可见，最多可遮挡4个区域。
          type: page
        type: navigation
      stream:
        desc: 设置>显示>码流
        name: 码流
        subpage:
          clear:
            desc: 设置>显示>码流>码流>清晰
            name: 清晰
            subpage:
              desc: 设置>显示>码流>码流>清晰
              frame_rate:
                desc: 设置>显示>码流>码流>清晰>帧率(FPS)
                name: 帧率(FPS)
                options:
                - '25'
                - '22'
                - '20'
                - '18'
                - '16'
                - 15(默认)
                - '12'
                - '10'
                - 取消
                text:
                - 帧率(FPS)
                - 每秒钟的帧数，越高画面越流畅
                type: popup
              max_bit_rate:
                desc: 设置>显示>码流>码流>清晰>最大码率(Kbps)
                options:
                - 4096(默认)
                - '5120'
                - '6144'
                - '7168'
                - '8192'
                - 取消
                text:
                - 最大码率(Kbps)
                - 相同的分辨率、帧率下，码率越大画质越好，网络要求也越高
                type: popup
              name: 清晰
              resolution:
                desc: 设置>显示>码流>码流>清晰>分辨率
                name: 分辨率
                options:
                - 3840*2160
                - 取消
                text:
                - 分辨率
                - 越高视频越清晰
                - 取消
                type: popup
              text:
              - 取消
              - 清晰
              - 保存
              - 分辨率
              - 帧率(FPS)
              - 最大码率(Kbps)
              type: page
            type: navigation
          desc: 设置>显示>码流>码流
          fluent:
            desc: 设置>显示>码流>码流>流畅
            name: 流畅
            subpage:
              desc: 设置>显示>码流>码流>流畅
              frame_rate:
                desc: 设置>显示>码流>码流>流畅>帧率(FPS)
                name: 帧率(FPS)
                options:
                - '20'
                - '18'
                - '16'
                - 15(默认)
                - '12'
                - '8'
                - '6'
                - '4'
                - 取消
                text:
                - 帧率(FPS)
                - 每秒钟的帧数，越高画面越流畅
                type: popup
              max_bit_rate:
                desc: 设置>显示>码流>码流>流畅>最大码率(Kbps)
                options:
                - '128'
                - '256'
                - '384'
                - '512'
                - '672'
                - 768(默认)
                - '1024'
                - '1228'
                - 取消
                text:
                - 最大码率(Kbps)
                - 相同的分辨率、帧率下，码率越大画质越好，网络要求也越高
                type: popup
              name: 流畅
              resolution:
                desc: 设置>显示>码流>码流>流畅>分辨率
                name: 分辨率
                options:
                - 896*512
                - 取消
                text:
                - 分辨率
                - 越高视频越清晰
                - 取消
                type: popup
              type: page
            type: navigation
          frame_rate_mode:
            desc: 设置>显示>码流>码流>帧率控制
            name: 帧率控制
            options:
            - 自动
            - 恒定
            - 取消
            text:
            - 帧率控制
            - 自动
            - 可变帧率，自动调节帧率来保持画质（不适用有快速运动的物体）。
            - 恒定
            - 恒定帧率，流畅优先。
            - 取消
            type: popup
          name: 码流
          text:
          - 码流
          - 清晰
          - 分辨率
          - 帧率(FPS)
          - 最大码率(Kbps)
          - 流畅
          - 帧率控制
          type: navigation
        type: navigation
      vertical_flip:
        desc: 设置>显示>垂直翻转
        name: 垂直翻转
        options:
        - switch_on
        - switch_off
        type: switch
      watermark:
        desc: 设置>显示>水印
        name: 水印
        options:
        - switch_on
        - switch_off
        type: switch
    name: 显示
    type: navigation
sub_name: ''
