wifi_page:
  name: 'Wi-Fi'
  key: 'wifi_page'
  desc: 'Wi-Fi页面-入口：设置>Wi-Fi'
  type: 'page'
  items:
    wifi_band:
      name: 'Wi-Fi 频段偏好'
      desc: '设置>Wi-Fi>Wi-Fi 频段偏好'
      type: 'checkbox'
      options:
        - '自动'
        - '仅 5G'
        - '仅 2.json.4G'
    wifi_speed_test:
      name: 'Wi-Fi测速'
      desc: '设置>Wi-Fi>Wi-Fi测速'
      type: 'navigation'
      subpage:
        name: 'Wi-Fi测速'
        desc: '设置>Wi-Fi>Wi-Fi测速>Wi-Fi测速'
        type: 'page'
