device_list_name: "Reolink Video Doorbell WiFi Whi"
uid: '952700Y0058Y1MGY'
sub_name: ""

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        name: '灯'
        desc: '设置>灯主页'
        type: 'page'
        text:
          - '灯'
          - '红外灯'
          - '按钮灯'

        infrared_light:
          name: '红外灯'
          desc: '设置>灯>红外灯'
          type: 'navigation'
          subpage:
            name: '红外灯'
            desc: '设置>灯>红外灯'
            type: 'page'
            text:
              - '红外灯'
              - '红外补光灯，能让你在夜晚或光线较暗时拍出更清晰的影像。'
              - '红外灯关闭'
              - '红外灯亮起'
              - '自动'
              - '光线较暗时自动开启，光线较亮时自动关闭。'
              - '保持关闭'
            options_text:
              - '自动'
              - '保持关闭'

        button_light:
          name: '按钮灯'
          desc: '设置>灯>按钮灯'
          type: 'navigation'
          subpage:
            name: '按钮灯'
            desc: '设置>灯>按钮灯'
            type: 'page'
            text:
              - '按钮灯'
              - '仅连接电源时，按钮灯为白色。同时连接电源和网络时，按钮灯为蓝色。'
              - '了解更多'
              - '关闭'
              - '按钮灯将保持关闭'
              - '自动'
              - '按钮灯会自动在侦测到人、按压按钮和对讲时有灯光的反馈。'
              - '自动且夜间常亮'
              - '按钮灯将在检测到人员、按下按钮和双向通话时 24/7 亮起，并在夜间保持稳定的白色。'

            light_off_mode:
              name: '关闭'
              desc: '设置>灯>按钮灯>关闭'
              type: 'menu'

            light_auto_mode:
              name: '自动'
              desc: '设置>灯>按钮灯>自动'
              type: 'menu'

            light_auto_on_night_mode:
              name: '自动且夜间常亮'
              desc: '设置>灯>按钮灯>自动且夜间常亮'
              type: 'menu'

            light_always_on_mode:
              name: '常亮'
              desc: '设置>灯>按钮灯>自动且夜间常亮'
              type: 'menu'