device_list_name: "Reolink Video Doorbell-137Z"
uid: '952700Y0061K137Z'

ipc:
  email_alerts:
    name: '邮件通知'
    desc: '设置>邮件通知'
    type: 'navigation'
    text:
      - ''

    items:
      email_alerts:
        name: '邮件通知主页'
        desc: '设置>邮件通知>邮件通知主页(当前模块只需配置supported_test)'
        type: 'page'
        text:
          - ''
        options:
          - ''
        supported_test: '是否支持测试按钮，支持就保留该键，否则删除'

      plan:
        alarm_type:
          name: '报警类型'
          desc: '设置>邮件通知>计划主页>报警>报警类型(只需要配置options)'
          options:
            - '响铃'
            - '人'
            - '车'
            - '包裹'
            - '其他'

      email_config:
        name: '邮件设置'
        desc: '设置>邮件通知>邮件设置（无需配置）'
        type: 'navigation'
        text:
          - ''

      email_content:
        name: '邮件内容'
        desc: '设置>邮件通知>邮件内容(只需要配置是否支持移动轨迹和分辨率)'
        type: 'popup'
        text:
          - ''
        supported_move_track: false
        supported_resolution: false

      email_not_received:
        name: '未收到邮件？'
        desc: '设置>邮件通知>未收到邮件？（无需配置）'
        type: 'page'


