device_list_name: "952700Y101JN1AA1"
uid: '952700Y101JN1AA1'

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        name: '灯'
        desc: '设置>灯主页'
        type: 'page'
        text:
          - '指示灯'
          - '红外灯'
          - '按钮灯'

        status_lights:
          name: '指示灯'
          desc: '设置>灯>指示灯'
          type: 'navigation'
          text:
            - '指示灯'
            - '位于镜头附近的一个表示摄像机连接状态的灯。'
            - '了解更多'
            - '关闭'
            - '指示灯将保持关闭'
            - '开启'
            - '指示灯将始终亮起'
          options:
            - '开启'
            - '关闭'

          light_off_mode:
            name: '关闭'
          light_on_mode:
            name: '开启'

        infrared_light:
          name: '红外灯'
          desc: '设置>灯>红外灯'
          type: 'navigation'
          text:
            - '红外灯'
            - '红外灯补光时，能让你在夜晚或光线较暗时拍出更清晰的影像。'
            - '关'
            - '开'
            - '关闭'
            - '关闭红外灯后，夜视环境下效果会较差。'
            - '自动'
            - '光线较亮时自动开启，光线较暗时自动关闭。'
          options:
            - '关闭'
            - '自动'

        button_light:
          name: '按钮灯'
          desc: '设置>灯>按钮灯'
          type: 'navigation'
          text:
            - '按钮灯'
            - '按钮周围的一圈表示门铃连接状态的灯。'
            - '了解更多'
            - '关闭'
            - '按钮灯将保持关闭'
            - '自动'
            - '按钮灯会自动在侦测到人、按压按钮和对讲时有灯光的反馈。'
            - '自动且夜视常亮'
            - '按钮灯将在检测到人员、按下按钮和双向通话时 24/7 亮起，并在夜间保持稳定的白色。'
            - '常亮'
            - '按钮灯将始终亮起'
          options:
            - '自动'
            - '自动且夜视常亮'
            - '保持关闭'

          light_off_mode:
            name: '关闭'
            desc: '设置>灯>按钮灯>关闭'
            type: 'menu'

          light_auto_mode:
            name: '自动'
            desc: '设置>灯>按钮灯>自动'
            type: 'menu'

          light_auto_on_night_mode:
            name: '自动且夜间常亮'
            desc: '设置>灯>按钮灯>自动且夜间常亮'
            type: 'menu'

          light_always_on_mode:
            name: '常亮'
            desc: '设置>灯>按钮灯>自动且夜间常亮'
            type: 'menu'
