device_list_name: "yulong-test-sd7"
sub_name: ""

ipc:
  push:
    name: '手机推送'
    desc: '设置>手机推送'
    type: 'switch'
    text:
      - ''

    items:
      push:
        name: '手机推送'
        desc: '设置>手机推送'
        type: 'switch'
        push_text:
          - '手机推送'
          - '测试'
          - '打开后，将会接收到移动事件与低电量通知。'

      schedule:
        name: '计划'
        desc: '设置>手机推送>计划'
        type: 'navigation'
        push_text:
          - '计划'
          - '可筛选报警类型或时间进行规划。'
        text:
          - '取消'
          - '计划'
          - '保存'
          - '配置推送的触发类型和时间计划。'
          - '报警类型'
        alarm_type:
          name: '报警类型'
          desc: '设置>手机推送>计划>报警类型'
          type: 'page'
          text:
            - '取消'
            - '报警类型'
            - '保存'
            - '全选'
            - '画面变动'
            - '人'
            - '车'
            - '动物'
          option_text:
            - '画面变动'
            - '人'
            - '车'
            - '动物'

      push_interval:
        name: '推送间隔'
        desc: '设置>手机推送>推送间隔'
        type: 'popup'
        text:
          - '推送间隔(秒)'
          - '20'
          - '30'
          - '60'
          - '120'
          - '取消'
        option_text:
          - '20'
          - '30'
          - '60'
          - '120'

