device_list_name: "yulong-test-sd7"
sub_name: ""

ipc:
  sounds:
    name: '音频'
    desc: '设置>音频'
    type: 'navigation'
    items:
      record_audio:
        name: '录制声音'
        desc: '设置>音频'
        type: 'switch'
        text:
          - '关闭后，观看预览时将无法听到声音，并且将不会录制声音到回放文件中'
        options:
          - 'switch_on'
          - 'switch_off'

      adjust_alarm_and_speaker_volume:
        name: '设备音量'
        desc: '设置>音频'
        type: 'slider'
        text:
          - '报警音量和对讲音量'
        options:
          - ''

      sound_test:
        name: '试听'
        desc: '设置>音频'
        type: 'button'
        options:
          - ''

      noise_reduction:
        name: '音频降噪'
        desc: '设置>音频'
        type: 'switch'
        options:
          - 'switch_on'
          - 'switch_off'