device_list_name: "yulong-test-sd7"
sub_name: ""

ipc:
  camera_record:
    name: '摄像机录像'
    desc: '设置>摄像机录像'
    type: 'navigation'
    alarm_recording_text:
      - '摄像机录像'
      - '报警录像'
      - '定时录像'
      - '报警录像计划'
      - '配置报警录像（检测到报警事件时触发录像）的触发类型和时间计划。'
      - '录像延时时长'
      - '触发事件停止后延后录制的时长'
      - '覆盖录像'
      - '打开时，当容量不足时，新生成的录像将覆盖最旧的录像。'
    timed_recording_text:
      - '摄像机录像'
      - '报警录像'
      - '定时录像'
      - '定时录像计划'
      - '配置持续录像的时间计划，启用的时间段会持续不间断录像。'

    items:
      alarm_recording_plan:
        name: '报警录像计划'
        desc: '设置>摄像机录像>报警录像>报警录像计划'
        type: 'navigation'
        text:
          - '取消'
          - '报警录像计划'
          - '保存'
          - '配置报警录像（检测到报警事件时触发录像）的触发类型和时间计划。'
          - '报警类型'

        alarm_type:
          desc: '设置>摄像机录像>报警录像>报警录像计划>报警类型'
          type: 'navigation'
          text:
            - '报警类型'
            - '保存'
            - '全选'
            - '画面变动'
            - '人'
            - '车'
            - '动物'

      record_delay_duration:
        name: '录像延时时长'
        desc: '设置>摄像机录像>报警录像>录像延时时长'
        type: 'popup'
        text:
          - '录像延时时长'
          - '延时越长，能耗越大。'
          - '15 秒'
          - '30 秒'
          - '1 分'
        option_text:
          - '15 秒'
          - '30 秒'
          - '1 分'

      overwrite_record:
        name: '覆盖录像'
        desc: '设置>摄像机录像>报警录像>覆盖录像'
        type: 'popup'
        text:
          - ''
        option_text:
          - ''

      timed_recording_plan:
        name: '定时录像计划'
        desc: '设置>摄像机录像>定时录像>定时录像计划'
        type: 'navigation'
        text:
          - '取消'
          - '定时录像计划'
          - '保存'
          - '配置持续录像的时间计划，启用的时间段会持续不间断录像。'































schedule_page: &schedule_page_anchor
  name: '计划'
  desc: '设置>摄像机录像>计划>计划'
  type: 'page'
  items:
    alarm_type:
      name: '报警类型'
      desc: '设置>摄像机录像>计划>计划>报警类型'
      type: 'checkbox'
      options:
        - '画面变动'
        - '车'
        - '动物'
        - '包裹'


camera_record_page:
  name: '摄像机录像'
  desc: '设置>摄像机录像页面'
  type: 'page'
  items:
    camera_record:
      name: '摄像机录像'
      desc: '设置>摄像机录像>摄像机录像'
      type: 'switch'
    schedule:
      name: '计划'
      key: 'schedule'
      desc: '设置>摄像机录像>计划'
      type: 'navigation'
      subpage: *schedule_page_anchor
    record_delay_duration:
      name: '录像延时时长'
      desc: '设置>摄像机录像>录像延时时长'
      type: 'popup'
      options:
        - '15秒'
        - '30秒'
        - '1分'
    overwrite_record:
      name: '覆盖录像'
      key: ''
      desc: '设置>摄像机录像>覆盖录像'
      type: 'popup'
      options:
        - '1 天'
        - '2.json 天'
        - '3 天'
        - '7 天'
        - '14 天'
        - '30 天'
        - '循环覆盖最早的录像'
        - '无'

