device_list_name: "yulong-test-sd7"
sub_name: ""
access_mode: "single"
menu_item: '显示'
desc: '设置>显示'
type: 'page'
items:
  - menu_item: '垂直翻转'
    key: ''
    desc: '设置-显示-垂直翻转'
    type: 'switch'
    options: []
  - menu_item: '水平翻转'
    key: ''
    desc: '设置-显示-水平翻转'
    type: 'switch'
    options: []
  - menu_item: '码流'
    key: ''
    desc: '设置-显示-码流'
    type: 'navigation'
    options: []
    subpage:
      - menu_item: '清晰'
        element:
          - name: '分辨率'
          - name: '帧率(fps)'
          - name: '最大码率(kbps)'
          -

