device_list_name: "yulong-test-sd7"
sub_name: ""

ipc:
  email_alerts:
    name: '邮件通知'
    desc: '设置>邮件通知'
    type: 'navigation'
    text:
      - ''

    items:
      email_alerts:
        name: '邮件通知主页'
        desc: '设置>邮件通知>邮件通知主页'
        type: 'page'
        text:
          - '邮件通知'
          - '测试'
          - '检测到移动事件时，自动发送邮件提醒用户。'
          - '计划'
          - '可筛选报警类型或进行时间规划。'
          - '邮件设置'
          - '邮件内容'
          - '邮箱间隔'
          - '未收到邮件？'

      plan:
        name: '计划'
        desc: '设置>邮件通知>计划主页'
        type: 'navigation'
        text:
          - ''

        alarm:
          name: '报警'
          desc: '设置>邮件通知>计划主页>报警'
          type: 'tab'
          text:
            - '取消'
            - '计划'
            - '保存'
            - '报警'
            - '定时'
            - '配置报警邮件（检测到报警事件时发送邮件通知）的触发类型和时间计划。'
            - '报警类型'
          subpage:
            name: '报警类型'
            desc: '设置>邮件通知>计划主页>报警>报警类型'
            type: 'page'
            option_text:
              - '画面变动'
              - '人'
              - '车'
              - '动物'
        timed:
          name: '定时'
          desc: '设置>邮件通知>计划主页>定时'
          type: 'tab'
          text:
            - '取消'
            - '计划'
            - '保存'
            - '报警'
            - '定时'
            - '配置定时发送邮件的时间计划，启用的时间段内会按照一定的邮件间隔定时发送邮件。'

      email_config:
        name: '邮件设置'
        desc: '设置>邮件通知>邮件设置'
        type: 'navigation'
        text:
          - '邮件设置'
          - '清空'
          - '发件邮箱'
          - '收件邮箱'
          - '添加邮箱'

      email_content:
        name: '邮件内容'
        desc: '设置>邮件通知>邮件内容'
        type: 'popup'
        text:
          - '文字'
          - '图片'
          - '图片和文字'
          - '视频和文字'

      email_interval:
        name: '邮箱间隔'
        desc: '设置>邮件通知>邮箱间隔'
        type: 'popup'
        text:
          - '30 秒'
          - '1 分'
          - '5 分'
          - '10 分'
          - '30 分'

      email_not_received:
        name: '未收到邮件？'
        desc: '设置>邮件通知>未收到邮件？'
        type: 'page'
        text:
          - ''

