device_list_name: 'yulong-test-sd7'
sub_name: ''

ipc:
  Wi_Fi:
    name: 'Wi-Fi'
    desc: '设置>Wi-Fi'
    type: 'page'
    items:
      wifi_band_preference:
        name: 'Wi-Fi 频段偏好'
        key: 'wifi_band_preference'
        desc: '设置>Wi-Fi>Wi-Fi 频段偏好'
        type: 'popup'
        options:
          - '自动'
          - '仅 5G'
          - '仅 2.4G'
          - '取消'

      wifi_speed_test:
        name: 'Wi-Fi测速'
        desc: '设置>Wi-Fi>Wi-Fi测速'
        type: 'navigation'
        subpage:
          name: 'Wi-Fi测速'
          desc: '设置>Wi-Fi>Wi-Fi测速>Wi-Fi测速'
          type: 'button'
          text:
            - '1. 关闭手机移动数据，将手机与设备连接至同一个网络。'
            - '2. 点击“开始测速”测试Wi-Fi信号强度，并将手机和设备尽量靠近路由器。'
            - '3. 查看Wi-Fi信号强度测试结果，正常情况下，需要保证Wi-Fi信号强度在10Mbps以上（总值100Mbps）。'
          options:
            - '开始测速'

      disconnect:
        name: '未连接'
        key: 'disconnect'
        desc: '设置>Wi-Fi>未连接'
        type: 'text'

      add_other_network:
        name: '添加其他网络'
        key: 'add_other_network'
        desc: '设置>Wi-Fi>添加其他网络'
        type: 'navigation'
        subpage:
          name: '输入密码'
          key: 'input_password'
          desc: '设置>Wi-Fi>添加其他网络>输入密码'
          type: 'page'
          text:
            - '取消'
            - '保存'
            - 'Wi-Fi名称'
            - 'Wi-Fi密码'
            - '输入密码'
          options:
            input_wifi_name: 'reolink-HMK_5G'
            input_wifi_passw: '11111111'

hub:
  Wi_Fi:
    name: 'Wi-Fi'
    desc: '设置>Wi-Fi'
    type: 'page'
    items:
      wifi_band_preference:
        name: 'Wi-Fi 频段偏好'
        key: 'wifi_band_preference'
        desc: '设置>Wi-Fi>Wi-Fi 频段偏好'
        type: 'popup'
        options:
          - '自动'
          - '仅 5G'
          - '仅 2.4G'
          - '取消'

      wifi_speed_test:
        name: 'Wi-Fi测速'
        desc: '设置>Wi-Fi>Wi-Fi测速'
        type: 'navigation'
        subpage:
          name: 'Wi-Fi测速'
          desc: '设置>Wi-Fi>Wi-Fi测速>Wi-Fi测速'
          type: 'button'
          text:
            - '1. 关闭手机移动数据，将手机与设备连接至同一个网络。'
            - '2. 点击“开始测速”测试Wi-Fi信号强度，并将手机和设备尽量靠近路由器。'
            - '3. 查看Wi-Fi信号强度测试结果，正常情况下，需要保证Wi-Fi信号强度在10Mbps以上（总值100Mbps）。'
          options:
            - '开始测速'

      disconnect:
        name: '未连接'
        key: 'disconnect'
        desc: '设置>Wi-Fi>未连接'
        type: 'text'

      add_other_network:
        name: '添加其他网络'
        key: 'add_other_network'
        desc: '设置>Wi-Fi>添加其他网络'
        type: 'navigation'
        subpage:
          name: '输入密码'
          key: 'input_password'
          desc: '设置>Wi-Fi>添加其他网络>输入密码'
          type: 'page'
          text:
            - '取消'
            - '保存'
            - 'Wi-Fi名称'
            - 'Wi-Fi密码'
            - '输入密码'
          options:
            input_wifi_name: 'reolink-HMK_5G'
            input_wifi_passw: '11111111'

nvr:
  Wi_Fi:
    name: 'Wi-Fi'
    desc: '设置>Wi-Fi'
    type: 'page'
    items:
      wifi_band_preference:
        name: 'Wi-Fi 频段偏好'
        key: 'wifi_band_preference'
        desc: '设置>Wi-Fi>Wi-Fi 频段偏好'
        type: 'popup'
        options:
          - '自动'
          - '仅 5G'
          - '仅 2.4G'
          - '取消'

      wifi_speed_test:
        name: 'Wi-Fi测速'
        desc: '设置>Wi-Fi>Wi-Fi测速'
        type: 'navigation'
        subpage:
          name: 'Wi-Fi测速'
          desc: '设置>Wi-Fi>Wi-Fi测速>Wi-Fi测速'
          type: 'button'
          text:
            - '1. 关闭手机移动数据，将手机与设备连接至同一个网络。'
            - '2. 点击“开始测速”测试Wi-Fi信号强度，并将手机和设备尽量靠近路由器。'
            - '3. 查看Wi-Fi信号强度测试结果，正常情况下，需要保证Wi-Fi信号强度在10Mbps以上（总值100Mbps）。'
          options:
            - '开始测速'

      disconnect:
        name: '未连接'
        key: 'disconnect'
        desc: '设置>Wi-Fi>未连接'
        type: 'text'

      add_other_network:
        name: '添加其他网络'
        key: 'add_other_network'
        desc: '设置>Wi-Fi>添加其他网络'
        type: 'navigation'
        subpage:
          name: '输入密码'
          key: 'input_password'
          desc: '设置>Wi-Fi>添加其他网络>输入密码'
          type: 'page'
          text:
            - '取消'
            - '保存'
            - 'Wi-Fi名称'
            - 'Wi-Fi密码'
            - '输入密码'
          options:
            input_wifi_name: 'reolink-HMK_5G'
            input_wifi_passw: '11111111'