device_list_name: "yulong-test-sd7"
name: 'Wi-Fi'
model: 'Reolink TrackMix WiFi'
desc: '设置>Wi-Fi'
type: 'page'
items:
  - name: 'Wi-Fi 频段偏好'
    key: 'wifi_band_preference'
    desc: '设置>Wi-Fi>Wi-Fi 频段偏好'
    type: 'navigation'
    option:
      - '自动'
      - '仅 5G'
      - '仅 2.4G'
      - '取消'
  - name: 'Wi-Fi测速'
    key:
    desc:
    type: 'navigation'
    option:
      - '开始测速'
  - name: '输入密码'
    option:
      - 'wifi名称'
      - 'wifi密码'