device_list_name: "Reolink Duo 2"
uid: '952700Y004CWC5JO'

ipc:
  display:
    name: '显示'
    desc: '设置>显示'
    type: 'navigation'

    items:
      display:
        name: '显示'
        desc: '设置>显示'
        type: 'navigation'
        text:
          - '码流'
          - '移动标记'
          - '画面为清晰时，智能检测到移动事物将进行标记。'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'
        options:
          - '码流'
          - '移动标记'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'

        stream:
          text:
            - '码流'
            - '清晰'
            - '分辨率'
            - '帧率(FPS)'
            - '最大码率(kbps)'
            - '流畅'

          clear:
            text:
              - ''

            resolution:
              name: '分辨率'
              desc: '设置>显示>码流>码流>清晰>分辨率'
              type: 'popup'
              text:
                - '分辨率'
                - '越高视频越清晰'
                - '4608*1728'
              options:
                - '4608*1728'

            frame_rate:
              name: '帧率(FPS)'
              desc: '设置>显示>码流>码流>清晰>帧率(FPS)'
              type: 'popup'
              text:
                - '帧率(FPS)'
                - '每秒钟的帧数，越高画面越流畅'
                - '15(默认)'
                - '12'
                - '10'
              options:
                - '15(默认)'
                - '12'
                - '10'

            max_bit_rate:
              name: '最大码率(kbps)'
              desc: '设置>显示>码流>码流>清晰>最大码率(Kbps)'
              type: 'popup'
              text:
                - '最大码率(Kbps)'
                - '相同的分辨率、帧率下，码率越大画质越好，网络要求也越高'
                - '1024'
                - '1536'
                - '2048(默认)'
                - '3072'
                - '4096'
              options:
                - '1024'
                - '1536'
                - '2048(默认)'
                - '3072'
                - '4096'

            i_frame_interval:
              name: 'i帧间隔'
              desc: '设置>显示>码流>码流>清晰>i帧间隔'
              type: 'popup'
              text:
                - 'i帧间隔'
                - 'I帧间隔小，视频质量高，但文件大。I帧间隔大，文件小，但质量低。'
                - '1x'
                - '2x'
              options:
                - '1x'
                - '2x'

          fluent:
            text:
              - ''

            resolution:
              name: '分辨率'
              desc: '设置>显示>码流>码流>流畅>分辨率'
              type: 'popup'
              text:
                - '分辨率'
                - '越高视频越清晰'
                - '1536*576'
              options:
                - '1536*576'

            frame_rate:
              name: '帧率(FPS)'
              desc: '设置>显示>码流>码流>流畅>帧率(FPS)'
              type: 'popup'
              text:
                - '帧率(FPS)'
                - '每秒钟的帧数，越高画面越流畅'
                - '15(默认)'
                - '10'
              options:
                - '15(默认)'
                - '10'

            max_bit_rate:
              desc: '设置>显示>码流>码流>流畅>最大码率(kbps)'
              type: 'popup'
              text:
                - '最大码率(kbps)'
                - '相同的分辨率、帧率下，码率越大画质越好，网络要求也越高'
                - '64'
                - '128'
                - '160'
                - '192'
                - '256'
                - '384'
                - '512'
                - '672(默认)'
              options:
                - '64'
                - '128'
                - '160'
                - '192'
                - '256'
                - '384'
                - '512'
                - '672(默认)'

            i_frame_interval:
              name: 'i帧间隔'
              desc: '设置>显示>码流>码流>流畅>i帧间隔'
              type: 'popup'
              text:
                - 'i帧间隔'
                - 'I帧间隔小，视频质量高，但文件大。I帧间隔大，文件小，但质量低。'
                - '1x'
                - '2x'
                - '3x'
                - '4x'
              options:
                - '1x'
                - '2x'
                - '3x'
                - '4x'

        motion_mark:
          name: '移动标记'
          desc: '设置>显示>移动标记'
          type: 'switch'
          text:
            - '移动标记'
            - '画面为清晰时，智能检测到移动事物将进行标记。'
          options:
            - 'switch-on'
            - 'switch-off'

        device_name:
          name: '设备名称'
          desc: '设置>显示>设备名称'
          type: 'popup'
          text:
            - '设备名称'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'
          options:
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'

        date:
          name: '日期'
          desc: '设置>显示>日期'
          type: 'popup'
          text:
            - '日期'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'
          options:
            - '隐藏'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'

        watermark:
          name: '水印'
          desc: '设置>显示>水印'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        image_setting:
          name: '图像设置(只需要确认亮度同步/hdr/夜视通透模式/抗闪烁)'

          brightness: '亮度'
          contrast: '对比度'
          saturation: '饱和度'
          sharpness: '锐度'
          brightness_sync: false
          hdr: false
          night_transparent_vision: false
          anti_flicker: true

        day_and_night:
          name: '白天和黑夜'
          desc: '白天和黑夜'
          type: 'popup'
          text:
            - '白天和黑夜'
            - '模式切换'
            - '高光/阴影调节'
            - '黑白'
            - '白天彩色'
            - '夜视彩色'
          options:
            - '模式切换'
            - '黑白'
            - '白天彩色'
            - '夜视彩色'

          mode_switching:
            name: '模式切换'
            desc: '白天和黑夜>模式切换'
            type: 'popup'
            text:
              - '模式切换'
              - '黑白'
              - '彩色'
              - '自动'
              - '光线较亮时自动显示彩色，较暗时自动显示黑白。'
              - '恢复默认值'
              - '0'
              - '100'
            options:
              - '黑白'
              - '彩色'
              - '自动'

          day_color:
            name: '白天彩色'
            desc: '白天和黑夜>白天彩色'
            type: 'popup'
            text:
              - '白天彩色'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

          black_and_white:
            name: '黑白'
            desc: '白天和黑夜>黑白'
            type: 'popup'
            text:
              - '黑白'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

          night_vision_color:
            name: '夜视彩色'
            desc: '白天和黑夜>夜视彩色'
            type: 'popup'
            text:
              - '夜视彩色'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

        splice_region:
          name: '拼接区域'

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 8
