device_list_name: "Argus PT Ultra Sd93"
uid: '952700Y002PO3HHP'

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        name: '灯'
        desc: '设置>灯主页'
        type: 'page'
        text:
          - '状态灯'
          - '红外灯'
          - '白光灯'

        status_lights:
          name: '状态灯'
          desc: '设置>灯>状态灯'
          type: 'navigation'
          text:
            - '状态灯'
            - '位于镜头附近的一个表示摄像机连接状态的灯。'
            - '了解更多'
            - '关闭'
            - '状态灯将保持关闭'
            - '开启'
            - '状态灯将始终亮起'
          options:
            - '开启'
            - '关闭'

          light_off_mode:
            name: '关闭'
          light_on_mode:
            name: '开启'

        infrared_light:
          name: '红外灯'
          desc: '设置>灯>红外灯'
          type: 'navigation'
          text:
            - '红外灯'
            - '红外灯补光时，能让你在夜晚或光线较暗时拍出更清晰的影像。'
            - '关'
            - '开'
            - '关闭'
            - '关闭红外灯后，夜视环境下效果会较差。'
            - '自动'
            - '光线较亮时自动开启，光线较暗时自动关闭。'
          options:
            - '关闭'
            - '自动'

        floodlight:
          name: '白光灯'
          desc: '设置>灯>白光灯'
          type: 'navigation'
          text:
            - '关闭'
            - '白光灯将保持关闭'
            - '夜间智能模式'
            - '当相机在夜间检测到事件时自动打开。'
            - '预览自动开启'
            - '夜晚查看预览时，自动开启，结束后关闭。'
          options:
            - '关闭'
            - '夜间智能模式'
            - '预览自动开启'

          light_off_mode:
            name: '关闭'
            desc: '设置>灯>白光灯>关闭'
            type: 'menu'
            text:
              - ''

          night_smart_mode:
            name: '夜间智能模式'
            desc: '设置>灯>照明灯>夜间智能模式'
            type: 'menu'
            text:
              - ''
            detect_type:
              desc: '设置>灯>照明灯>夜间智能模式>侦测'
              type: 'navigation'
              text:
                - '报警类型'
                - '保存'
                - '全选'
                - '画面变动'
                - '人'
                - '车'
                - '动物'
              option_text:
                - '人'
                - '车'
                - '动物'

          preview_opens_auto:
            name: '预览自动开启'
            desc: '设置>灯>照明灯>预览自动开启'
            type: 'switch'
