device_list_name: "Argus PT Ultra"
uid: '952700Y002PO3HHP'
sub_name: ""

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        name: '灯'
        desc: '设置>灯主页'
        type: 'page'
        text:
          - '灯'
          - '状态灯'
          - '红外灯'
          - '照明灯'

        status_lights:
          name: '状态灯'
          desc: '设置>灯>状态灯'
          type: 'navigation'
          subpage:
            name: '状态灯'
            desc: '设置>灯>状态灯'
            type: 'page'
            text:
              - '状态灯'
              - '位于镜头附近的一个表示摄像机连接状态的灯。'
              - '了解更多'
              - '关闭'
              - '状态灯将保持关闭'
              - '开启'
              - '状态灯将始终亮起'

            light_off_mode:
              name: '关闭'
              desc: '设置>灯>状态灯>关闭'
              type: 'menu'

            light_on_mode:
              name: '开启'
              desc: '设置>灯>状态灯>开启'
              type: 'menu'

        infrared_light:
          name: '红外灯'
          desc: '设置>灯>红外灯'
          type: 'navigation'
          subpage:
            name: '红外灯'
            desc: '设置>灯>红外灯'
            type: 'page'
            text:
              - '红外灯'
              - '红外补光灯，能让你在夜晚或光线较暗时拍出更清晰的影像。'
              - '红外灯关闭'
              - '红外灯亮起'
              - '自动'
              - '光线较暗时自动开启，光线较亮时自动关闭。'
              - '保持关闭'
            options_text:
              - '自动'
              - '保持关闭'

