device_list_name: "Argus 4 Pro"
uid: '952700Y100EC720C'

ipc:
  display:
    name: '显示'
    desc: '设置>显示'
    type: 'navigation'

    items:
      display:
        name: '显示'
        desc: '设置>显示'
        type: 'navigation'
        text:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '移动标记'
          - '画面为清晰时，智能检测到移动事物将进行标记。'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'
        options:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '移动标记'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'

        vertical_flip: '垂直翻转'


        horizontal_flip: '水平翻转'


        stream:
          text:
            - ''
          options:
            - ''

          clear:
            text:
              - 'i帧间隔'

            resolution:
              name: '分辨率'
              options:
                - '5120*1440'

            frame_rate:
              name: '帧率(FPS)'
              options:
                - '15(默认)'
                - '12'
                - '10'

            max_bit_rate:
              name: '最大码率(kbps)'
              options:
                - '1024'
                - '1536'
                - '2048(默认)'
                - '3072'
                - '4096'

            i_frame_interval:
              name: 'i帧间隔'
              options:
                - '1x'
                - '2x'

          fluent:
            text:
              - 'i帧间隔'

            resolution:
              name: '分辨率'
              options:
                - '1536*432'

            frame_rate:
              name: '帧率(FPS)'
              options:
                - '15(默认)'
                - '10'

            max_bit_rate:
              name: '最大码率(kbps)'
              options:
                - '256'
                - '512(默认)'
                - '1024'

            i_frame_interval:
              name: 'i帧间隔'
              options:
                - '1x'
                - '2x'
                - '3x'
                - '4x'

        motion_mark: '移动标记'

        device_name: '设备名称'

        date: '日期'

        watermark: '水印'

        image_setting:
          name: '图像设置(只需要确认亮度同步/hdr/夜视通透模式/抗闪烁)'

          brightness: '亮度'
          contrast: '对比度'
          saturation: '饱和度'
          sharpness: '锐度'
          brightness_sync: false
          hdr: false
          night_transparent_vision: false
          anti_flicker: true

        day_and_night:
          name: '白天和黑夜'
          desc: '白天和黑夜'
          type: 'popup'
          text:
            - '白天和黑夜'
            - '模式切换'
            - '高光/阴影调节'
            - '白天彩色'
            - '夜视彩色'
          options:
            - '模式切换'
            - '白天彩色'
            - '夜视彩色'

          mode_switching:
            name: '模式切换'
            desc: '白天和黑夜>模式切换'
            type: 'popup'
            text:
              - '模式切换'
              - '日夜切换阈值'
              - '白天和黑夜自动模式下，黑白彩色切换的环境亮度阈值：'
              - '恢复默认值'
              - '0'
              - '100'
            options:
              - '日夜切换阈值'

          day_color:
            name: '白天彩色'
            desc: '白天和黑夜>白天彩色'
            type: 'popup'
            text:
              - '白天彩色'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

          night_vision_color:
            name: '夜视彩色'
            desc: '白天和黑夜>夜视彩色'
            type: 'popup'
            text:
              - '夜视彩色'
              - '自动'
              - '手动'
              - '亮度'
              - '恢复默认值'
              - '暗部'
              - '0'
              - '255'
            options:
              - '自动'
              - '手动'
              - '亮度'
              - '暗部'

        splice_region: '拼接区域'

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 8
