device_list_name: "CX410"
uid: '952700Y005K15KA1'
sub_name: ""

ipc:
  light:
    name: '灯'
    desc: '设置>灯'
    type: 'navigation'
    text:
      - ''

    items:
      light:
        name: '灯'
        desc: '设置>灯'
        type: 'page'
        text:
          - '照明灯'

        floodlight:
          name: '照明灯'
          desc: '设置>灯>照明灯'
          type: 'navigation'
          subpage:
            name: '照明灯'
            desc: '设置>灯>照明灯'
            type: 'page'

            light_off_mode:
              name: '关闭'
              desc: '设置>灯>照明灯>关闭'
              type: 'menu'
              text:
                - '白光灯'
                - '夜晚时开启照明灯画面呈彩色状态，拍摄效果更佳。'
                - '关闭'
                - '白光灯将保持关闭'
                - '定时模式'
                - '在预定的时间段内保持开启。'
                - '自动模式'
                - '根据环境光照条件自动调整亮度以获得最佳夜视效果。'
                - '智能模式'
                - '自动调整亮度以在弱光条件下进行准确检测，并在预定时间段内摄像机检测到事件时开启。'

            timer_mode:
              name: '定时模式'
              desc: '设置>灯>照明灯>定时模式'
              type: 'menu'
              text:
                - '白光灯'
                - '夜晚时开启照明灯画面呈彩色状态，拍摄效果更佳。'
                - '关闭'
                - '白光灯将保持关闭'
                - '自动模式'
                - '根据环境光照条件自动调整亮度以获得最佳夜视效果。'
                - '定时模式'
                - '在预定的时间段内保持开启。'
                - '开始时间'
                - '结束时间'
                - '智能模式'
                - '自动调整亮度以在弱光条件下进行准确检测，并在预定时间段内摄像机检测到事件时开启。'

            auto_mode:
              name: '自动模式'
              desc: '设置>灯>照明灯>自动模式'
              type: 'menu'
              text:
                - '白光灯'
                - '夜晚时开启照明灯画面呈彩色状态，拍摄效果更佳。'
                - '关闭'
                - '白光灯将保持关闭'
                - '定时模式'
                - '在预定的时间段内保持开启。'
                - '自动模式'
                - '根据环境光照条件自动调整亮度以获得最佳夜视效果。'
                - '智能模式'
                - '自动调整亮度以在弱光条件下进行准确检测，并在预定时间段内摄像机检测到事件时开启。'

            smart_mode:
              name: '智能模式'
              desc: '设置>灯>照明灯>智能模式'
              type: 'menu'
              text:
                - '白光灯'
                - '夜晚时开启照明灯画面呈彩色状态，拍摄效果更佳。'
                - '关闭'
                - '白光灯将保持关闭'
                - '定时模式'
                - '在预定的时间段内保持开启。'
                - '自动模式'
                - '根据环境光照条件自动调整亮度以获得最佳夜视效果。'
                - '智能模式'
                - '自动调整亮度以在弱光条件下进行准确检测，并在预定时间段内摄像机检测到事件时开启。'
                - '侦测'
                - '开始时间'
                - '结束时间'

              detect_type:
                desc: '设置>灯>照明灯>夜间智能模式>侦测'
                type: 'navigation'
                text:
                  - '报警类型'
                  - '保存'
                  - '全选'
                  - '画面变动'
                  - '人'
                  - '车'
                  - '动物'
                option_text:
                  - '人'
                  - '车'
                  - '动物'
