device_list_name: "Reolink Argus 2E"
uid: '952700Y000U78TQO'

ipc:
  display:
    name: '显示'
    desc: '设置>显示'
    type: 'navigation'

    items:
      display:
        name: '显示'
        desc: '设置>显示'
        type: 'navigation'
        text:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'
        options:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'

        vertical_flip:
          name: '垂直翻转'
          desc: '设置>显示>垂直翻转'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        horizontal_flip:
          name: '水平翻转'
          desc: '设置>显示>水平翻转'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        stream:
          name: '码流'
          desc: '设置>显示>码流'
          type: 'navigation'
          subpage:
            name: '码流'
            desc: '设置>显示>码流>码流'
            type: 'navigation'
            text:
              - '码流'
              - '清晰'
              - '分辨率'
              - '帧率(FPS)'
              - '最大码率(kbps)'
              - '流畅'
              - 'i帧间隔'

            clear:
              name: '清晰'
              desc: '设置>显示>码流>码流>清晰'
              type: 'navigation'
              subpage:
                name: '清晰'
                desc: '设置>显示>码流>码流>清晰'
                type: 'page'
                text:
                  - '取消'
                  - '清晰'
                  - '保存'
                  - '分辨率'
                  - '帧率(fps)'
                  - '最大码率(kbps)'
                  - 'i帧间隔'

                resolution:
                  name: '分辨率'
                  desc: '设置>显示>码流>码流>清晰>分辨率'
                  type: 'popup'
                  text:
                    - '分辨率'
                    - '越高视频越清晰'
                    - '1920*1080'
                    - '1280*720'
                  options:
                    - '1920*1080'
                    - '1280*720'

                frame_rate:
                  name: '帧率(FPS)'
                  desc: '设置>显示>码流>码流>清晰>帧率(FPS)'
                  type: 'popup'
                  text:
                    - '帧率(FPS)'
                    - '每秒钟的帧数，越高画面越流畅'
                    - '15(默认)'
                    - '10'
                    - '5'
                    - '2'
                  options:
                    - '15(默认)'
                    - '10'
                    - '5'
                    - '2'

                max_bit_rate:
                  name: '最大码率(kbps)'
                  desc: '设置>显示>码流>码流>清晰>最大码率(Kbps)'
                  type: 'popup'
                  text:
                    - '最大码率(Kbps)'
                    - '相同的分辨率、帧率下，码率越大画质越好，网络要求也越高'
                    - '256'
                    - '512'
                    - '768'
                    - '1024'
                    - '1536(默认)'
                    - '2048'
                  options:
                    - '256'
                    - '512'
                    - '768'
                    - '1024'
                    - '1536(默认)'
                    - '2048'

                i_frame_interval:
                  name: 'i帧间隔'
                  desc: '设置>显示>码流>码流>清晰>i帧间隔'
                  type: 'popup'
                  text:
                    - 'i帧间隔'
                    - 'I帧间隔小，视频质量高，但文件大。I帧间隔大，文件小，但质量低。'
                    - '1x'
                    - '2x'
                  options:
                    - '1x'
                    - '2x'

            fluent:
              name: '流畅'
              desc: '设置>显示>码流>码流>流畅'
              type: 'navigation'
              subpage:
                name: '流畅'
                desc: '设置>显示>码流>码流>流畅'
                type: 'page'
                text:
                  - '取消'
                  - '流畅'
                  - '保存'
                  - '分辨率'
                  - '帧率(fps)'
                  - '最大码率(kbps)'
                  - 'i帧间隔'

                resolution:
                  name: '分辨率'
                  desc: '设置>显示>码流>码流>流畅>分辨率'
                  type: 'popup'
                  text:
                    - '分辨率'
                    - '越高视频越清晰'
                    - '640*360'
                  options:
                    - '640*360'

                frame_rate:
                  name: '帧率(FPS)'
                  desc: '设置>显示>码流>码流>流畅>帧率(FPS)'
                  type: 'popup'
                  text:
                    - '帧率(FPS)'
                    - '每秒钟的帧数，越高画面越流畅'
                    - '15'
                    - '10'
                    - '5(默认)'
                    - '2'
                  options:
                    - '15'
                    - '10'
                    - '5(默认)'
                    - '2'

                max_bit_rate:
                  desc: '设置>显示>码流>码流>流畅>最大码率(kbps)'
                  type: 'popup'
                  text:
                    - '最大码率(kbps)'
                    - '相同的分辨率、帧率下，码率越大画质越好，网络要求也越高'
                    - '64'
                    - '128'
                    - '160(默认)'
                    - '192'
                    - '256'
                    - '384'
                    - '512'
                  options:
                    - '64'
                    - '128'
                    - '160(默认)'
                    - '192'
                    - '256'
                    - '384'
                    - '512'

                interval_frame:
                  name: 'i帧间隔'
                  desc: '设置>显示>码流>码流>流畅>i帧间隔'
                  type: 'popup'
                  text:
                    - 'i帧间隔'
                    - 'I帧间隔小，视频质量高，但文件大。I帧间隔大，文件小，但质量低。'
                    - '1x'
                    - '2x'
                    - '3x'
                    - '4x'
                  options:
                    - '1x'
                    - '2x'
                    - '3x'
                    - '4x'

        device_name:
          name: '设备名称'
          desc: '设置>显示>设备名称'
          type: 'popup'
          text:
            - '设备名称'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'
          options:
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'

        date:
          name: '日期'
          desc: '设置>显示>日期'
          type: 'popup'
          text:
            - '日期'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'
          options:
            - '隐藏'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'

        watermark:
          name: '水印'
          desc: '设置>显示>水印'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        image_setting:
          name: '图像设置'
          desc: '设置>显示>图像设置'
          type: 'page'
          text:
            - '亮度'
            - '抗闪烁'
            - '调整摄像机的拍摄帧率，以减少受到画面中光源闪烁的影响。'
            - '0'
            - '255'

          brightness:
            name: '亮度'

          anti_flicker:
            name: '抗闪烁'
            desc: '设置>显示>抗闪烁'
            type: 'popup'
            text:
              - '抗闪烁'
              - '50HZ'
              - '60HZ'
              - '其他'
              - '关闭'
            options:
              - '50HZ'
              - '60HZ'
              - '其他'
              - '关闭'

        day_and_night:
          name: '白天和黑夜'
          desc: '白天和黑夜'
          type: 'popup'
          text:
            - '白天和黑夜'
            - '模式切换'
          options:
            - '模式切换'

          mode_switching:
            name: '模式切换'
            desc: '白天和黑夜>模式切换'
            type: 'popup'
            text:
              - '模式切换'
              - '黑白'
              - '彩色'
              - '自动'
              - '光线较亮时自动显示彩色，较暗时自动显示黑白。'
              - '恢复默认值'
              - '0'
              - '100'
            options:
              - '黑白'
              - '彩色'
              - '自动'

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          text:
            - '取消'
            - '遮盖区域'
            - '保存'
            - '清空所有'
          user_tips:
            - '在画面中通过手指滑动添加黑色遮挡区域，监控视频中的遮挡区域将不可见，最多可遮挡3个区域。'
            - '我知道了'
