device_list_name: "Reolink Argus 2E"
uid: '952700Y000U78TQO'

ipc:
  display:
    name: '显示'
    desc: '设置>显示'
    type: 'navigation'

    items:
      display:
        name: '显示'
        desc: '设置>显示'
        type: 'navigation'
        text:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'
        options:
          - '垂直翻转'
          - '水平翻转'
          - '码流'
          - '设备名称'
          - '日期'
          - '水印'
          - '图像设置'
          - '白天和黑夜'
          - '遮盖区域'

        vertical_flip:
          name: '垂直翻转'
          desc: '设置>显示>垂直翻转'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        horizontal_flip:
          name: '水平翻转'
          desc: '设置>显示>水平翻转'
          type: 'switch'
          options:
            - 'switch_on'
            - 'switch_off'

        stream:
          text:
            - ''
          options:
            - ''

          clear:
            text:
              - ''

            resolution:
              name: '分辨率'
              options:
                - '1920*1080'
                - '1280*720'

            frame_rate:
              name: '帧率(FPS)'
              options:
                - '15(默认)'
                - '10'
                - '5'
                - '2'

            max_bit_rate:
              name: '最大码率(kbps)'
              options:
                - '256'
                - '512'
                - '768'
                - '1024'
                - '1536(默认)'
                - '2048'

          fluent:
            text:
              - ''

            resolution:
              name: '分辨率'
              options:
                - '640*360'

            frame_rate:
              name: '帧率(FPS)'
              options:
                - '15'
                - '10'
                - '5(默认)'
                - '2'

            max_bit_rate:
              desc: '设置>显示>码流>码流>流畅>最大码率(kbps)'
              options:
                - '64'
                - '128'
                - '160(默认)'
                - '192'
                - '256'
                - '384'
                - '512'

            i_frame_interval:
              name: 'i帧间隔'
              options:
                - '1x'
                - '2x'
                - '3x'
                - '4x'

        device_name:
          name: '设备名称'
          options:
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'
            - '隐藏'

        date:
          name: '日期'
          options:
            - '隐藏'
            - '左上'
            - '中上'
            - '右上'
            - '左下'
            - '中下'
            - '右下'

        watermark:
          name: '水印'

        image_setting:
          name: '图像设置(只需要确认亮度同步/hdr/夜视通透模式/抗闪烁)'

          brightness: '亮度'
#          contrast: '对比度'
#          saturation: '饱和度'
#          sharpness: '锐度'
          brightness_sync: false
          hdr: false
          night_transparent_vision: false
          anti_flicker: true

        day_and_night:
          name: '白天和黑夜'
          desc: '白天和黑夜'
          type: 'popup'
          text:
            - '白天和黑夜'
            - '模式切换'
          options:
            - '模式切换'

          mode_switching:
            name: '模式切换'
            desc: '白天和黑夜>模式切换'
            type: 'popup'
            text:
              - '模式切换'
              - '黑白'
              - '彩色'
              - '自动'
              - '光线较亮时自动显示彩色，较暗时自动显示黑白。'
              - '恢复默认值'
              - '0'
              - '100'
            options:
              - '黑白'
              - '彩色'
              - '自动'

        private_mark:
          name: '遮盖区域'
          desc: '设置>显示>遮盖区域'
          type: 'navigation'
          camera_type: 'DM'
          mask_num: 3
